// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: portunus/v1/portunus.proto
//
// NOTE: If you modify the .proto service definition, re-run:
//   protoc --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/portunus/v1/portunus.proto

package portunusv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ─── Client ─────────────────────────────────────────────────────────────────

// PortunusServiceClient is the client API for PortunusService.
type PortunusServiceClient interface {
	// SendHeartbeat records a module health telemetry tick.
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// RequestAccess evaluates a card-read event and returns an access decision.
	RequestAccess(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessResponse, error)
}

type portunusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortunusServiceClient(cc grpc.ClientConnInterface) PortunusServiceClient {
	return &portunusServiceClient{cc}
}

func (c *portunusServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, PortunusService_SendHeartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portunusServiceClient) RequestAccess(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessResponse, error) {
	out := new(AccessResponse)
	err := c.cc.Invoke(ctx, PortunusService_RequestAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ─── Server ─────────────────────────────────────────────────────────────────

// PortunusServiceServer is the server API for PortunusService.
// All implementations must embed UnimplementedPortunusServiceServer.
type PortunusServiceServer interface {
	// SendHeartbeat records a module health telemetry tick.
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// RequestAccess evaluates a card-read event and returns an access decision.
	RequestAccess(context.Context, *AccessRequest) (*AccessResponse, error)
	mustEmbedUnimplementedPortunusServiceServer()
}

// UnimplementedPortunusServiceServer must be embedded for forward compatibility.
type UnimplementedPortunusServiceServer struct{}

func (UnimplementedPortunusServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedPortunusServiceServer) RequestAccess(context.Context, *AccessRequest) (*AccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAccess not implemented")
}
func (UnimplementedPortunusServiceServer) mustEmbedUnimplementedPortunusServiceServer() {}

// UnsafePortunusServiceServer may be embedded to opt out of forward compatibility.
type UnsafePortunusServiceServer interface {
	mustEmbedUnimplementedPortunusServiceServer()
}

// ─── Registration ───────────────────────────────────────────────────────────

const PortunusService_SendHeartbeat_FullMethodName = "/portunus.v1.PortunusService/SendHeartbeat"
const PortunusService_RequestAccess_FullMethodName = "/portunus.v1.PortunusService/RequestAccess"

var PortunusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portunus.v1.PortunusService",
	HandlerType: (*PortunusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _PortunusService_SendHeartbeat_Handler,
		},
		{
			MethodName: "RequestAccess",
			Handler:    _PortunusService_RequestAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portunus/v1/portunus.proto",
}

func RegisterPortunusServiceServer(s grpc.ServiceRegistrar, srv PortunusServiceServer) {
	s.RegisterService(&PortunusService_ServiceDesc, srv)
}

// ─── Handlers ───────────────────────────────────────────────────────────────

func _PortunusService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortunusServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortunusService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortunusServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortunusService_RequestAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortunusServiceServer).RequestAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortunusService_RequestAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortunusServiceServer).RequestAccess(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}
