// Portunus — shared message contract
//
// This file is the single source of truth for the wire format between the
// Portunus server and ESP32 access modules.  Both sides generate code from
// this file:
//
//   Server (Go):  protoc  + protoc-gen-go
//   ESP32  (C):   protoc  + nanopb generator  (see ../nanopb/portunus.options)
//
// The access module sends Nanopb-encoded messages to the server using one
// of two transport modes (selected at build time via Kconfig):
//
//   1. gRPC over HTTP/2+TLS (CONFIG_PORTUNUS_USE_GRPC=y, recommended):
//      Uses nghttp2 + esp-tls on the ESP32 to speak the gRPC wire protocol.
//      Connects to the PortunusService defined below.
//
//   2. HTTP/1.1+TLS with protobuf (legacy / fallback):
//      POSTs Nanopb-encoded messages with Content-Type: application/x-protobuf
//      and an HMAC-SHA256 signature header (X-Portunus-Sig).
//
// The PortunusService block below is the canonical RPC contract.  The wire
// encoding (request/response message types) is identical whether the
// transport is gRPC or the HTTP/1.1 path, keeping both in sync.
//
// ─── Compatibility rules ───────────────────────────────────────────────────
//   • Only APPEND new fields (never reorder or reuse a field number).
//   • Mark removed fields as `reserved`.
//   • Keep optional semantics where the ESP32 may not have the data
//     (e.g. door_closed before a reed-switch is wired).
// ───────────────────────────────────────────────────────────────────────────

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: portunus/v1/portunus.proto

package portunusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status codes for ProvisionCredentialResponse.
type ProvisionStatus int32

const (
	ProvisionStatus_PROVISION_STATUS_UNSPECIFIED ProvisionStatus = 0
	ProvisionStatus_PROVISION_STATUS_SUCCESS     ProvisionStatus = 1
	// credential_hash is already assigned to an active member.
	ProvisionStatus_PROVISION_STATUS_DUPLICATE_ACTIVE ProvisionStatus = 2
	// credential_hash exists but belongs to an expired or archived member.
	ProvisionStatus_PROVISION_STATUS_DUPLICATE_INACTIVE ProvisionStatus = 3
	// credential_hash is attached to a pending_authorization record.
	ProvisionStatus_PROVISION_STATUS_DUPLICATE_PENDING ProvisionStatus = 4
	// Operator does not have provisioning permission.
	ProvisionStatus_PROVISION_STATUS_UNAUTHORIZED ProvisionStatus = 5
	// role_id does not exist on the server.
	ProvisionStatus_PROVISION_STATUS_INVALID_ROLE ProvisionStatus = 6
	// Capture path: new pending_authorization record created, awaiting admin approval.
	ProvisionStatus_PROVISION_STATUS_PENDING_CREATED ProvisionStatus = 7
)

// Enum value maps for ProvisionStatus.
var (
	ProvisionStatus_name = map[int32]string{
		0: "PROVISION_STATUS_UNSPECIFIED",
		1: "PROVISION_STATUS_SUCCESS",
		2: "PROVISION_STATUS_DUPLICATE_ACTIVE",
		3: "PROVISION_STATUS_DUPLICATE_INACTIVE",
		4: "PROVISION_STATUS_DUPLICATE_PENDING",
		5: "PROVISION_STATUS_UNAUTHORIZED",
		6: "PROVISION_STATUS_INVALID_ROLE",
		7: "PROVISION_STATUS_PENDING_CREATED",
	}
	ProvisionStatus_value = map[string]int32{
		"PROVISION_STATUS_UNSPECIFIED":        0,
		"PROVISION_STATUS_SUCCESS":            1,
		"PROVISION_STATUS_DUPLICATE_ACTIVE":   2,
		"PROVISION_STATUS_DUPLICATE_INACTIVE": 3,
		"PROVISION_STATUS_DUPLICATE_PENDING":  4,
		"PROVISION_STATUS_UNAUTHORIZED":       5,
		"PROVISION_STATUS_INVALID_ROLE":       6,
		"PROVISION_STATUS_PENDING_CREATED":    7,
	}
)

func (x ProvisionStatus) Enum() *ProvisionStatus {
	p := new(ProvisionStatus)
	*p = x
	return p
}

func (x ProvisionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProvisionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_portunus_v1_portunus_proto_enumTypes[0].Descriptor()
}

func (ProvisionStatus) Type() protoreflect.EnumType {
	return &file_portunus_v1_portunus_proto_enumTypes[0]
}

func (x ProvisionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProvisionStatus.Descriptor instead.
func (ProvisionStatus) EnumDescriptor() ([]byte, []int) {
	return file_portunus_v1_portunus_proto_rawDescGZIP(), []int{0}
}

// Provisioning mode sent by the PEU firmware in ProvisionCredentialRequest.
type ProvisionMode int32

const (
	ProvisionMode_PROVISION_MODE_UNSPECIFIED ProvisionMode = 0
	// Capture path: no operator badge — new member record created as
	// pending_authorization and queued for admin approval.
	ProvisionMode_PROVISION_MODE_CAPTURE ProvisionMode = 1
	// Operator-enrol path: operator badge (scan 1) authorises the new member
	// (scan 2) directly into the active state.
	ProvisionMode_PROVISION_MODE_OPERATOR_ENROLL ProvisionMode = 2
)

// Enum value maps for ProvisionMode.
var (
	ProvisionMode_name = map[int32]string{
		0: "PROVISION_MODE_UNSPECIFIED",
		1: "PROVISION_MODE_CAPTURE",
		2: "PROVISION_MODE_OPERATOR_ENROLL",
	}
	ProvisionMode_value = map[string]int32{
		"PROVISION_MODE_UNSPECIFIED":     0,
		"PROVISION_MODE_CAPTURE":         1,
		"PROVISION_MODE_OPERATOR_ENROLL": 2,
	}
)

func (x ProvisionMode) Enum() *ProvisionMode {
	p := new(ProvisionMode)
	*p = x
	return p
}

func (x ProvisionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProvisionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_portunus_v1_portunus_proto_enumTypes[1].Descriptor()
}

func (ProvisionMode) Type() protoreflect.EnumType {
	return &file_portunus_v1_portunus_proto_enumTypes[1]
}

func (x ProvisionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProvisionMode.Descriptor instead.
func (ProvisionMode) EnumDescriptor() ([]byte, []int) {
	return file_portunus_v1_portunus_proto_rawDescGZIP(), []int{1}
}

// Sent by the access module at a regular interval to report health
// telemetry and confirm connectivity.
//
// Server Go equivalent: types.HeartbeatRequest
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the access module (required).
	// Corresponds to PORTUNUS_MAX_NAME_LEN (32 chars) on the device.
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// Firmware version string, e.g. "0.1.0-mvp".
	FirmwareVersion string `protobuf:"bytes,2,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	// Seconds since the module booted (esp_timer / 1e6 on ESP32).
	// uint64 matches the Go type; the ESP32 populates the lower 32 bits.
	UptimeS uint64 `protobuf:"varint,3,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	// Reed-switch state.  Omitted when no reed switch is installed.
	DoorClosed *bool `protobuf:"varint,4,opt,name=door_closed,json=doorClosed,proto3,oneof" json:"door_closed,omitempty"`
	// WiFi RSSI in dBm.  Omitted when unavailable.
	RssiDbm *int32 `protobuf:"varint,5,opt,name=rssi_dbm,json=rssiDbm,proto3,oneof" json:"rssi_dbm,omitempty"`
	// IP address of the module (IPv4 dotted-quad or IPv6).
	Ip string `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	// Free heap in bytes at the time of the heartbeat.
	FreeHeapBytes uint32 `protobuf:"varint,7,opt,name=free_heap_bytes,json=freeHeapBytes,proto3" json:"free_heap_bytes,omitempty"`
	// Monotonically increasing heartbeat counter (resets on reboot).
	Sequence      uint32 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_portunus_v1_portunus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portunus_v1_portunus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_portunus_v1_portunus_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *HeartbeatRequest) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *HeartbeatRequest) GetUptimeS() uint64 {
	if x != nil {
		return x.UptimeS
	}
	return 0
}

func (x *HeartbeatRequest) GetDoorClosed() bool {
	if x != nil && x.DoorClosed != nil {
		return *x.DoorClosed
	}
	return false
}

func (x *HeartbeatRequest) GetRssiDbm() int32 {
	if x != nil && x.RssiDbm != nil {
		return *x.RssiDbm
	}
	return 0
}

func (x *HeartbeatRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HeartbeatRequest) GetFreeHeapBytes() uint32 {
	if x != nil {
		return x.FreeHeapBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Returned by the server to acknowledge the heartbeat.
//
// Server Go equivalent: types.HeartbeatResponse
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Always true on a successful heartbeat.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Whether the module_id is registered in the device registry.
	Known bool `protobuf:"varint,2,opt,name=known,proto3" json:"known,omitempty"`
	// Echoed module_id.
	ModuleId string `protobuf:"bytes,3,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// Server wall-clock time (RFC 3339 with nanoseconds).
	ServerTime    string `protobuf:"bytes,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_portunus_v1_portunus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portunus_v1_portunus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_portunus_v1_portunus_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *HeartbeatResponse) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *HeartbeatResponse) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

// Sent by the access module when a credential is presented to the reader.
//
// Server Go equivalent: types.AccessRequest
type AccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the access module (required).
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// Hex-encoded credential UID, e.g. "04:A3:2B:1C" (required).
	CredentialId string `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	// Reed-switch state at the moment of the read.
	DoorClosed *bool `protobuf:"varint,3,opt,name=door_closed,json=doorClosed,proto3,oneof" json:"door_closed,omitempty"`
	// Device-local timestamp of the read (ISO 8601 / RFC 3339).
	// Optional because the module may not have an RTC.
	RequestedAt   string `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_portunus_v1_portunus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portunus_v1_portunus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_portunus_v1_portunus_proto_rawDescGZIP(), []int{2}
}

func (x *AccessRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *AccessRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *AccessRequest) GetDoorClosed() bool {
	if x != nil && x.DoorClosed != nil {
		return *x.DoorClosed
	}
	return false
}

func (x *AccessRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

// Returned by the server with the access decision.
//
// Server Go equivalent: types.AccessResponse
type AccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the request was processed without internal error.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Whether the module_id is registered in the device registry.
	Known bool `protobuf:"varint,2,opt,name=known,proto3" json:"known,omitempty"`
	// The access decision: true = unlock, false = deny.
	Granted bool `protobuf:"varint,3,opt,name=granted,proto3" json:"granted,omitempty"`
	// Human-readable reason code included in the wire response.
	// Grant: "allow_all" | "credential_allowed"
	// Deny:  "denied" | "unknown_module" | "invalid_credential_format"
	//
	//	| "credential_not_found"
	//	| "member_expired" | "member_suspended" | "member_archived"
	//	| "member_disabled"
	//	| "module_not_authorized"
	//	| "authorization_revoked" | "authorization_expired"
	//
	// Longest value: "invalid_credential_format" (25 chars).
	// Nanopb max_size:33 (32 chars + NUL) — never add a reason longer than 32.
	// Note: "member_lookup_error" and "service_misconfigured" appear in the
	// audit log only; the service returns an error to the transport in those
	// cases and does not populate this field.
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Echoed module_id.
	ModuleId string `protobuf:"bytes,5,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// Server wall-clock time (RFC 3339 with nanoseconds).
	ServerTime    string `protobuf:"bytes,6,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessResponse) Reset() {
	*x = AccessResponse{}
	mi := &file_portunus_v1_portunus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessResponse) ProtoMessage() {}

func (x *AccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portunus_v1_portunus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessResponse.ProtoReflect.Descriptor instead.
func (*AccessResponse) Descriptor() ([]byte, []int) {
	return file_portunus_v1_portunus_proto_rawDescGZIP(), []int{3}
}

func (x *AccessResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AccessResponse) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *AccessResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *AccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AccessResponse) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *AccessResponse) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

// Sent by a provisioning console after a successful two-scan flow.
// The device sends raw RFID UID bytes for both scans; the server applies
// HMAC-SHA256 and resolves the scan-1 UID to a member_access record for
// attribution.
//
// Server Go equivalent: types.ProvisionCredentialRequest
type ProvisionCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module ID of the provisioning console.
	ModuleId string `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// Role ID to assign to the new member.  Must already exist on the server.
	RoleId string `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// Raw RFID UID bytes read from the new-member card (scan 2, 1–10 bytes).
	// The server computes HMAC-SHA256(secret, credential_uid) before storing.
	CredentialUid []byte `protobuf:"bytes,5,opt,name=credential_uid,json=credentialUid,proto3" json:"credential_uid,omitempty"`
	// Raw RFID UID bytes read from the operator's card (scan 1, 1–10 bytes).
	// The server hashes this and resolves the operator against member_access,
	// checking that the member's role carries member.provision permission.
	OperatorCredentialUid []byte `protobuf:"bytes,6,opt,name=operator_credential_uid,json=operatorCredentialUid,proto3" json:"operator_credential_uid,omitempty"`
	// Explicit provisioning mode selected by the PEU firmware.
	// When UNSPECIFIED the server infers the mode from operator_credential_uid
	// presence (empty = capture path, non-empty = operator-enrol path).
	ProvisionMode ProvisionMode `protobuf:"varint,7,opt,name=provision_mode,json=provisionMode,proto3,enum=portunus.v1.ProvisionMode" json:"provision_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionCredentialRequest) Reset() {
	*x = ProvisionCredentialRequest{}
	mi := &file_portunus_v1_portunus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionCredentialRequest) ProtoMessage() {}

func (x *ProvisionCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portunus_v1_portunus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionCredentialRequest.ProtoReflect.Descriptor instead.
func (*ProvisionCredentialRequest) Descriptor() ([]byte, []int) {
	return file_portunus_v1_portunus_proto_rawDescGZIP(), []int{4}
}

func (x *ProvisionCredentialRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ProvisionCredentialRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *ProvisionCredentialRequest) GetCredentialUid() []byte {
	if x != nil {
		return x.CredentialUid
	}
	return nil
}

func (x *ProvisionCredentialRequest) GetOperatorCredentialUid() []byte {
	if x != nil {
		return x.OperatorCredentialUid
	}
	return nil
}

func (x *ProvisionCredentialRequest) GetProvisionMode() ProvisionMode {
	if x != nil {
		return x.ProvisionMode
	}
	return ProvisionMode_PROVISION_MODE_UNSPECIFIED
}

// Returned by the server after processing a provisioning request.
//
// Server Go equivalent: types.ProvisionCredentialResponse
type ProvisionCredentialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID assigned to the new member record.  Non-empty on SUCCESS only.
	MemberUuid string          `protobuf:"bytes,1,opt,name=member_uuid,json=memberUuid,proto3" json:"member_uuid,omitempty"`
	Status     ProvisionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=portunus.v1.ProvisionStatus" json:"status,omitempty"`
	// Human-readable detail for duplicate/error cases (operator display).
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionCredentialResponse) Reset() {
	*x = ProvisionCredentialResponse{}
	mi := &file_portunus_v1_portunus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionCredentialResponse) ProtoMessage() {}

func (x *ProvisionCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portunus_v1_portunus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionCredentialResponse.ProtoReflect.Descriptor instead.
func (*ProvisionCredentialResponse) Descriptor() ([]byte, []int) {
	return file_portunus_v1_portunus_proto_rawDescGZIP(), []int{5}
}

func (x *ProvisionCredentialResponse) GetMemberUuid() string {
	if x != nil {
		return x.MemberUuid
	}
	return ""
}

func (x *ProvisionCredentialResponse) GetStatus() ProvisionStatus {
	if x != nil {
		return x.Status
	}
	return ProvisionStatus_PROVISION_STATUS_UNSPECIFIED
}

func (x *ProvisionCredentialResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_portunus_v1_portunus_proto protoreflect.FileDescriptor

const file_portunus_v1_portunus_proto_rawDesc = "" +
	"\n" +
	"\x1aportunus/v1/portunus.proto\x12\vportunus.v1\"\xac\x02\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12)\n" +
	"\x10firmware_version\x18\x02 \x01(\tR\x0ffirmwareVersion\x12\x19\n" +
	"\buptime_s\x18\x03 \x01(\x04R\auptimeS\x12$\n" +
	"\vdoor_closed\x18\x04 \x01(\bH\x00R\n" +
	"doorClosed\x88\x01\x01\x12\x1e\n" +
	"\brssi_dbm\x18\x05 \x01(\x05H\x01R\arssiDbm\x88\x01\x01\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip\x12&\n" +
	"\x0ffree_heap_bytes\x18\a \x01(\rR\rfreeHeapBytes\x12\x1a\n" +
	"\bsequence\x18\b \x01(\rR\bsequenceB\x0e\n" +
	"\f_door_closedB\v\n" +
	"\t_rssi_dbm\"w\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05known\x18\x02 \x01(\bR\x05known\x12\x1b\n" +
	"\tmodule_id\x18\x03 \x01(\tR\bmoduleId\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\tR\n" +
	"serverTime\"\xaa\x01\n" +
	"\rAccessRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\tR\fcredentialId\x12$\n" +
	"\vdoor_closed\x18\x03 \x01(\bH\x00R\n" +
	"doorClosed\x88\x01\x01\x12!\n" +
	"\frequested_at\x18\x04 \x01(\tR\vrequestedAtB\x0e\n" +
	"\f_door_closed\"\xa6\x01\n" +
	"\x0eAccessResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05known\x18\x02 \x01(\bR\x05known\x12\x18\n" +
	"\agranted\x18\x03 \x01(\bR\agranted\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1b\n" +
	"\tmodule_id\x18\x05 \x01(\tR\bmoduleId\x12\x1f\n" +
	"\vserver_time\x18\x06 \x01(\tR\n" +
	"serverTime\"\xa0\x02\n" +
	"\x1aProvisionCredentialRequest\x12\x1b\n" +
	"\tmodule_id\x18\x02 \x01(\tR\bmoduleId\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\tR\x06roleId\x12%\n" +
	"\x0ecredential_uid\x18\x05 \x01(\fR\rcredentialUid\x126\n" +
	"\x17operator_credential_uid\x18\x06 \x01(\fR\x15operatorCredentialUid\x12A\n" +
	"\x0eprovision_mode\x18\a \x01(\x0e2\x1a.portunus.v1.ProvisionModeR\rprovisionModeJ\x04\b\x01\x10\x02J\x04\b\x03\x10\x04R\roperator_uuidR\x0fcredential_hash\"\x8c\x01\n" +
	"\x1bProvisionCredentialResponse\x12\x1f\n" +
	"\vmember_uuid\x18\x01 \x01(\tR\n" +
	"memberUuid\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.portunus.v1.ProvisionStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail*\xb5\x02\n" +
	"\x0fProvisionStatus\x12 \n" +
	"\x1cPROVISION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PROVISION_STATUS_SUCCESS\x10\x01\x12%\n" +
	"!PROVISION_STATUS_DUPLICATE_ACTIVE\x10\x02\x12'\n" +
	"#PROVISION_STATUS_DUPLICATE_INACTIVE\x10\x03\x12&\n" +
	"\"PROVISION_STATUS_DUPLICATE_PENDING\x10\x04\x12!\n" +
	"\x1dPROVISION_STATUS_UNAUTHORIZED\x10\x05\x12!\n" +
	"\x1dPROVISION_STATUS_INVALID_ROLE\x10\x06\x12$\n" +
	" PROVISION_STATUS_PENDING_CREATED\x10\a*o\n" +
	"\rProvisionMode\x12\x1e\n" +
	"\x1aPROVISION_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROVISION_MODE_CAPTURE\x10\x01\x12\"\n" +
	"\x1ePROVISION_MODE_OPERATOR_ENROLL\x10\x022\x95\x02\n" +
	"\x0fPortunusService\x12N\n" +
	"\rSendHeartbeat\x12\x1d.portunus.v1.HeartbeatRequest\x1a\x1e.portunus.v1.HeartbeatResponse\x12H\n" +
	"\rRequestAccess\x12\x1a.portunus.v1.AccessRequest\x1a\x1b.portunus.v1.AccessResponse\x12h\n" +
	"\x13ProvisionCredential\x12'.portunus.v1.ProvisionCredentialRequest\x1a(.portunus.v1.ProvisionCredentialResponseB;Z9github.com/BrandonDHaskell/Portunus/server/api/portunusv1b\x06proto3"

var (
	file_portunus_v1_portunus_proto_rawDescOnce sync.Once
	file_portunus_v1_portunus_proto_rawDescData []byte
)

func file_portunus_v1_portunus_proto_rawDescGZIP() []byte {
	file_portunus_v1_portunus_proto_rawDescOnce.Do(func() {
		file_portunus_v1_portunus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portunus_v1_portunus_proto_rawDesc), len(file_portunus_v1_portunus_proto_rawDesc)))
	})
	return file_portunus_v1_portunus_proto_rawDescData
}

var file_portunus_v1_portunus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_portunus_v1_portunus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_portunus_v1_portunus_proto_goTypes = []any{
	(ProvisionStatus)(0),                // 0: portunus.v1.ProvisionStatus
	(ProvisionMode)(0),                  // 1: portunus.v1.ProvisionMode
	(*HeartbeatRequest)(nil),            // 2: portunus.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 3: portunus.v1.HeartbeatResponse
	(*AccessRequest)(nil),               // 4: portunus.v1.AccessRequest
	(*AccessResponse)(nil),              // 5: portunus.v1.AccessResponse
	(*ProvisionCredentialRequest)(nil),  // 6: portunus.v1.ProvisionCredentialRequest
	(*ProvisionCredentialResponse)(nil), // 7: portunus.v1.ProvisionCredentialResponse
}
var file_portunus_v1_portunus_proto_depIdxs = []int32{
	1, // 0: portunus.v1.ProvisionCredentialRequest.provision_mode:type_name -> portunus.v1.ProvisionMode
	0, // 1: portunus.v1.ProvisionCredentialResponse.status:type_name -> portunus.v1.ProvisionStatus
	2, // 2: portunus.v1.PortunusService.SendHeartbeat:input_type -> portunus.v1.HeartbeatRequest
	4, // 3: portunus.v1.PortunusService.RequestAccess:input_type -> portunus.v1.AccessRequest
	6, // 4: portunus.v1.PortunusService.ProvisionCredential:input_type -> portunus.v1.ProvisionCredentialRequest
	3, // 5: portunus.v1.PortunusService.SendHeartbeat:output_type -> portunus.v1.HeartbeatResponse
	5, // 6: portunus.v1.PortunusService.RequestAccess:output_type -> portunus.v1.AccessResponse
	7, // 7: portunus.v1.PortunusService.ProvisionCredential:output_type -> portunus.v1.ProvisionCredentialResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_portunus_v1_portunus_proto_init() }
func file_portunus_v1_portunus_proto_init() {
	if File_portunus_v1_portunus_proto != nil {
		return
	}
	file_portunus_v1_portunus_proto_msgTypes[0].OneofWrappers = []any{}
	file_portunus_v1_portunus_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portunus_v1_portunus_proto_rawDesc), len(file_portunus_v1_portunus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portunus_v1_portunus_proto_goTypes,
		DependencyIndexes: file_portunus_v1_portunus_proto_depIdxs,
		EnumInfos:         file_portunus_v1_portunus_proto_enumTypes,
		MessageInfos:      file_portunus_v1_portunus_proto_msgTypes,
	}.Build()
	File_portunus_v1_portunus_proto = out.File
	file_portunus_v1_portunus_proto_goTypes = nil
	file_portunus_v1_portunus_proto_depIdxs = nil
}
