// Portunus — shared message contract
//
// This file is the single source of truth for the wire format between the
// Portunus server and ESP32 access modules.  Both sides generate code from
// this file:
//
//   Server (Go):  protoc  + protoc-gen-go
//   ESP32  (C):   protoc  + nanopb generator  (see ../nanopb/portunus.options)
//
// The access module sends Nanopb-encoded messages to the server using one
// of two transport modes (selected at build time via Kconfig):
//
//   1. gRPC over HTTP/2+TLS (CONFIG_PORTUNUS_USE_GRPC=y, recommended):
//      Uses nghttp2 + esp-tls on the ESP32 to speak the gRPC wire protocol.
//      Connects to the PortunusService defined below.
//
//   2. HTTP/1.1+TLS with protobuf (legacy / fallback):
//      POSTs Nanopb-encoded messages with Content-Type: application/x-protobuf
//      and an HMAC-SHA256 signature header (X-Portunus-Sig).
//
// The PortunusService block below is the canonical RPC contract.  The wire
// encoding (request/response message types) is identical whether the
// transport is gRPC or the HTTP/1.1 path, keeping both in sync.
//
// ─── Compatibility rules ───────────────────────────────────────────────────
//   • Only APPEND new fields (never reorder or reuse a field number).
//   • Mark removed fields as `reserved`.
//   • Keep optional semantics where the ESP32 may not have the data
//     (e.g. door_closed before a reed-switch is wired).
// ───────────────────────────────────────────────────────────────────────────

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: portunus/v1/portunus.proto

package portunusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortunusService_SendHeartbeat_FullMethodName       = "/portunus.v1.PortunusService/SendHeartbeat"
	PortunusService_RequestAccess_FullMethodName       = "/portunus.v1.PortunusService/RequestAccess"
	PortunusService_ProvisionCredential_FullMethodName = "/portunus.v1.PortunusService/ProvisionCredential"
)

// PortunusServiceClient is the client API for PortunusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PortunusService is the canonical RPC interface.
//
// ESP32 access modules can use this via HTTP/2+TLS when the firmware is
// built with CONFIG_PORTUNUS_USE_GRPC=y.  The module's grpc_client
// component implements the gRPC wire protocol using nghttp2 + esp-tls.
//
// When CONFIG_PORTUNUS_USE_GRPC is disabled, modules fall back to
// HTTP/1.1 with the same protobuf messages and an HMAC signature header.
//
// Other intended consumers:
//   - Server-side admin CLIs
//   - Test harnesses (grpcurl, Go test clients)
//   - Future gateway / proxy components
type PortunusServiceClient interface {
	// SendHeartbeat records a module health telemetry tick.
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// RequestAccess evaluates a credential-read event and returns an access decision.
	RequestAccess(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessResponse, error)
	// ProvisionCredential processes a two-scan provisioning flow from a
	// PROVISIONING_CONSOLE firmware variant.
	ProvisionCredential(ctx context.Context, in *ProvisionCredentialRequest, opts ...grpc.CallOption) (*ProvisionCredentialResponse, error)
}

type portunusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortunusServiceClient(cc grpc.ClientConnInterface) PortunusServiceClient {
	return &portunusServiceClient{cc}
}

func (c *portunusServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, PortunusService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portunusServiceClient) RequestAccess(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessResponse)
	err := c.cc.Invoke(ctx, PortunusService_RequestAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portunusServiceClient) ProvisionCredential(ctx context.Context, in *ProvisionCredentialRequest, opts ...grpc.CallOption) (*ProvisionCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionCredentialResponse)
	err := c.cc.Invoke(ctx, PortunusService_ProvisionCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortunusServiceServer is the server API for PortunusService service.
// All implementations must embed UnimplementedPortunusServiceServer
// for forward compatibility.
//
// PortunusService is the canonical RPC interface.
//
// ESP32 access modules can use this via HTTP/2+TLS when the firmware is
// built with CONFIG_PORTUNUS_USE_GRPC=y.  The module's grpc_client
// component implements the gRPC wire protocol using nghttp2 + esp-tls.
//
// When CONFIG_PORTUNUS_USE_GRPC is disabled, modules fall back to
// HTTP/1.1 with the same protobuf messages and an HMAC signature header.
//
// Other intended consumers:
//   - Server-side admin CLIs
//   - Test harnesses (grpcurl, Go test clients)
//   - Future gateway / proxy components
type PortunusServiceServer interface {
	// SendHeartbeat records a module health telemetry tick.
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// RequestAccess evaluates a credential-read event and returns an access decision.
	RequestAccess(context.Context, *AccessRequest) (*AccessResponse, error)
	// ProvisionCredential processes a two-scan provisioning flow from a
	// PROVISIONING_CONSOLE firmware variant.
	ProvisionCredential(context.Context, *ProvisionCredentialRequest) (*ProvisionCredentialResponse, error)
	mustEmbedUnimplementedPortunusServiceServer()
}

// UnimplementedPortunusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortunusServiceServer struct{}

func (UnimplementedPortunusServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedPortunusServiceServer) RequestAccess(context.Context, *AccessRequest) (*AccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestAccess not implemented")
}
func (UnimplementedPortunusServiceServer) ProvisionCredential(context.Context, *ProvisionCredentialRequest) (*ProvisionCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionCredential not implemented")
}
func (UnimplementedPortunusServiceServer) mustEmbedUnimplementedPortunusServiceServer() {}
func (UnimplementedPortunusServiceServer) testEmbeddedByValue()                         {}

// UnsafePortunusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortunusServiceServer will
// result in compilation errors.
type UnsafePortunusServiceServer interface {
	mustEmbedUnimplementedPortunusServiceServer()
}

func RegisterPortunusServiceServer(s grpc.ServiceRegistrar, srv PortunusServiceServer) {
	// If the following call panics, it indicates UnimplementedPortunusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortunusService_ServiceDesc, srv)
}

func _PortunusService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortunusServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortunusService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortunusServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortunusService_RequestAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortunusServiceServer).RequestAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortunusService_RequestAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortunusServiceServer).RequestAccess(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortunusService_ProvisionCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortunusServiceServer).ProvisionCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortunusService_ProvisionCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortunusServiceServer).ProvisionCredential(ctx, req.(*ProvisionCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortunusService_ServiceDesc is the grpc.ServiceDesc for PortunusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortunusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portunus.v1.PortunusService",
	HandlerType: (*PortunusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _PortunusService_SendHeartbeat_Handler,
		},
		{
			MethodName: "RequestAccess",
			Handler:    _PortunusService_RequestAccess_Handler,
		},
		{
			MethodName: "ProvisionCredential",
			Handler:    _PortunusService_ProvisionCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portunus/v1/portunus.proto",
}
