/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PORTUNUS_V1_PORTUNUS_V1_PORTUNUS_PB_H_INCLUDED
#define PB_PORTUNUS_V1_PORTUNUS_V1_PORTUNUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Sent by the access module at a regular interval to report health
 telemetry and confirm connectivity.

 Server Go equivalent: types.HeartbeatRequest */
typedef struct _portunus_v1_HeartbeatRequest {
    /* Unique identifier for the access module (required).
 Corresponds to PORTUNUS_MAX_NAME_LEN (32 chars) on the device. */
    char module_id[33];
    /* Firmware version string, e.g. "0.1.0-mvp". */
    char firmware_version[24];
    /* Seconds since the module booted (esp_timer / 1e6 on ESP32).
 uint64 matches the Go type; the ESP32 populates the lower 32 bits. */
    uint64_t uptime_s;
    /* Reed-switch state.  Omitted when no reed switch is installed. */
    bool has_door_closed;
    bool door_closed;
    /* WiFi RSSI in dBm.  Omitted when unavailable. */
    bool has_rssi_dbm;
    int32_t rssi_dbm;
    /* IP address of the module (IPv4 dotted-quad or IPv6). */
    char ip[46];
    /* Free heap in bytes at the time of the heartbeat. */
    uint32_t free_heap_bytes;
    /* Monotonically increasing heartbeat counter (resets on reboot). */
    uint32_t sequence;
} portunus_v1_HeartbeatRequest;

/* Returned by the server to acknowledge the heartbeat.

 Server Go equivalent: types.HeartbeatResponse */
typedef struct _portunus_v1_HeartbeatResponse {
    /* Always true on a successful heartbeat. */
    bool ok;
    /* Whether the module_id is registered in the device registry. */
    bool known;
    /* Echoed module_id. */
    char module_id[33];
    /* Server wall-clock time (RFC 3339 with nanoseconds). */
    char server_time[40];
} portunus_v1_HeartbeatResponse;

/* Sent by the access module when a card is presented to the reader.

 Server Go equivalent: types.AccessRequest */
typedef struct _portunus_v1_AccessRequest {
    /* Unique identifier for the access module (required). */
    char module_id[33];
    /* Hex-encoded card UID, e.g. "04:A3:2B:1C" (required). */
    char card_id[30];
    /* Reed-switch state at the moment of the read. */
    bool has_door_closed;
    bool door_closed;
    /* Device-local timestamp of the read (ISO 8601 / RFC 3339).
 Optional because the module may not have an RTC. */
    char requested_at[40];
} portunus_v1_AccessRequest;

/* Returned by the server with the access decision.

 Server Go equivalent: types.AccessResponse */
typedef struct _portunus_v1_AccessResponse {
    /* True if the request was processed without internal error. */
    bool ok;
    /* Whether the module_id is registered in the device registry. */
    bool known;
    /* The access decision: true = unlock, false = deny. */
    bool granted;
    /* Human-readable reason code: "allow_all", "card_allowed",
 "card_not_allowed", "unknown_module", "denied". */
    char reason[33];
    /* Echoed module_id. */
    char module_id[33];
    /* Server wall-clock time (RFC 3339 with nanoseconds). */
    char server_time[40];
} portunus_v1_AccessResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define portunus_v1_HeartbeatRequest_init_default {"", "", 0, false, 0, false, 0, "", 0, 0}
#define portunus_v1_HeartbeatResponse_init_default {0, 0, "", ""}
#define portunus_v1_AccessRequest_init_default   {"", "", false, 0, ""}
#define portunus_v1_AccessResponse_init_default  {0, 0, 0, "", "", ""}
#define portunus_v1_HeartbeatRequest_init_zero   {"", "", 0, false, 0, false, 0, "", 0, 0}
#define portunus_v1_HeartbeatResponse_init_zero  {0, 0, "", ""}
#define portunus_v1_AccessRequest_init_zero      {"", "", false, 0, ""}
#define portunus_v1_AccessResponse_init_zero     {0, 0, 0, "", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define portunus_v1_HeartbeatRequest_module_id_tag 1
#define portunus_v1_HeartbeatRequest_firmware_version_tag 2
#define portunus_v1_HeartbeatRequest_uptime_s_tag 3
#define portunus_v1_HeartbeatRequest_door_closed_tag 4
#define portunus_v1_HeartbeatRequest_rssi_dbm_tag 5
#define portunus_v1_HeartbeatRequest_ip_tag      6
#define portunus_v1_HeartbeatRequest_free_heap_bytes_tag 7
#define portunus_v1_HeartbeatRequest_sequence_tag 8
#define portunus_v1_HeartbeatResponse_ok_tag     1
#define portunus_v1_HeartbeatResponse_known_tag  2
#define portunus_v1_HeartbeatResponse_module_id_tag 3
#define portunus_v1_HeartbeatResponse_server_time_tag 4
#define portunus_v1_AccessRequest_module_id_tag  1
#define portunus_v1_AccessRequest_card_id_tag    2
#define portunus_v1_AccessRequest_door_closed_tag 3
#define portunus_v1_AccessRequest_requested_at_tag 4
#define portunus_v1_AccessResponse_ok_tag        1
#define portunus_v1_AccessResponse_known_tag     2
#define portunus_v1_AccessResponse_granted_tag   3
#define portunus_v1_AccessResponse_reason_tag    4
#define portunus_v1_AccessResponse_module_id_tag 5
#define portunus_v1_AccessResponse_server_time_tag 6

/* Struct field encoding specification for nanopb */
#define portunus_v1_HeartbeatRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   module_id,         1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2) \
X(a, STATIC,   SINGULAR, UINT64,   uptime_s,          3) \
X(a, STATIC,   OPTIONAL, BOOL,     door_closed,       4) \
X(a, STATIC,   OPTIONAL, INT32,    rssi_dbm,          5) \
X(a, STATIC,   SINGULAR, STRING,   ip,                6) \
X(a, STATIC,   SINGULAR, UINT32,   free_heap_bytes,   7) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          8)
#define portunus_v1_HeartbeatRequest_CALLBACK NULL
#define portunus_v1_HeartbeatRequest_DEFAULT NULL

#define portunus_v1_HeartbeatResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                1) \
X(a, STATIC,   SINGULAR, BOOL,     known,             2) \
X(a, STATIC,   SINGULAR, STRING,   module_id,         3) \
X(a, STATIC,   SINGULAR, STRING,   server_time,       4)
#define portunus_v1_HeartbeatResponse_CALLBACK NULL
#define portunus_v1_HeartbeatResponse_DEFAULT NULL

#define portunus_v1_AccessRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   module_id,         1) \
X(a, STATIC,   SINGULAR, STRING,   card_id,           2) \
X(a, STATIC,   OPTIONAL, BOOL,     door_closed,       3) \
X(a, STATIC,   SINGULAR, STRING,   requested_at,      4)
#define portunus_v1_AccessRequest_CALLBACK NULL
#define portunus_v1_AccessRequest_DEFAULT NULL

#define portunus_v1_AccessResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                1) \
X(a, STATIC,   SINGULAR, BOOL,     known,             2) \
X(a, STATIC,   SINGULAR, BOOL,     granted,           3) \
X(a, STATIC,   SINGULAR, STRING,   reason,            4) \
X(a, STATIC,   SINGULAR, STRING,   module_id,         5) \
X(a, STATIC,   SINGULAR, STRING,   server_time,       6)
#define portunus_v1_AccessResponse_CALLBACK NULL
#define portunus_v1_AccessResponse_DEFAULT NULL

extern const pb_msgdesc_t portunus_v1_HeartbeatRequest_msg;
extern const pb_msgdesc_t portunus_v1_HeartbeatResponse_msg;
extern const pb_msgdesc_t portunus_v1_AccessRequest_msg;
extern const pb_msgdesc_t portunus_v1_AccessResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define portunus_v1_HeartbeatRequest_fields &portunus_v1_HeartbeatRequest_msg
#define portunus_v1_HeartbeatResponse_fields &portunus_v1_HeartbeatResponse_msg
#define portunus_v1_AccessRequest_fields &portunus_v1_AccessRequest_msg
#define portunus_v1_AccessResponse_fields &portunus_v1_AccessResponse_msg

/* Maximum encoded size of messages (where known) */
#define PORTUNUS_V1_PORTUNUS_V1_PORTUNUS_PB_H_MAX_SIZE portunus_v1_HeartbeatRequest_size
#define portunus_v1_AccessRequest_size           108
#define portunus_v1_AccessResponse_size          115
#define portunus_v1_HeartbeatRequest_size        142
#define portunus_v1_HeartbeatResponse_size       79

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
