/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "portunus/v1/portunus.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(portunus_v1_HeartbeatRequest, portunus_v1_HeartbeatRequest, AUTO)


PB_BIND(portunus_v1_HeartbeatResponse, portunus_v1_HeartbeatResponse, AUTO)


PB_BIND(portunus_v1_AccessRequest, portunus_v1_AccessRequest, AUTO)


PB_BIND(portunus_v1_AccessResponse, portunus_v1_AccessResponse, AUTO)



