/**
 * @file server_comm.cpp
 * @brief Server communication component — gRPC (HTTP/2 + TLS) transport.
 *
 * Architecture:
 *   Event bus callbacks (on_heartbeat_event / on_credential_event) copy
 *   incoming events into s_comm_queue.  The comm_task drains the queue,
 *   encodes protobuf, sends the request to the server via gRPC, and publishes
 *   the result (access decisions) back to the event bus.
 *
 *   A single persistent HTTP/2+TLS connection is reused across calls with
 *   exponential-backoff reconnect and periodic keepalive PINGs.
 *
 *   All I/O is blocking and runs entirely on the comm_task stack, so the
 *   event bus dispatcher is never blocked.
 */

#include "server_comm.hpp"
#include "event_bus.hpp"
#include "event_types.hpp"
#include "error_codes.hpp"
#include "network_config.hpp"
#include "security_config.hpp"
#include "wifi_mgr.hpp"
#include "portunus_types.hpp"
#include "credential_types.h"

/* Nanopb */
#include "portunus/v1/portunus.pb.h"
#include <pb_encode.h>
#include <pb_decode.h>

/* Provisioning: SHA-256 via mbedTLS (always available when mbedtls is linked) */
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
  #include "mbedtls/sha256.h"
#endif

/* ACCESS_POINT builds must use TLS: the response carries a door-grant decision
 * that is only authenticated at the application layer (HMAC) when TLS is also
 * present.  Without TLS, any on-path device can forge a granted=true response
 * even with HMAC fully enabled for outbound requests. */
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
  #if !PORTUNUS_USE_TLS
    #error "ACCESS_POINT firmware cannot be built without TLS (CONFIG_PORTUNUS_USE_TLS). " \
           "A door image without TLS has no authenticated server-to-device channel. " \
           "Enable TLS in menuconfig → Security Configuration."
  #endif
#endif

/* TLS / HMAC */
#if PORTUNUS_USE_TLS
  #if PORTUNUS_TLS_USE_CUSTOM_CA
    /* Embedded CA certificate for LAN TLS pinning.
     * The PEM is compiled into the binary by EMBED_TXTFILES in CMakeLists.txt.
     * Generated by: ./scripts/generate_certs.sh --ip <SERVER_IP> */
    extern const char ca_cert_pem_start[] asm("_binary_ca_cert_pem_start");
    extern const char ca_cert_pem_end[]   asm("_binary_ca_cert_pem_end");
  #else
    #include "esp_crt_bundle.h"
  #endif
#endif
#if PORTUNUS_HMAC_ENABLED
  #include "mbedtls/md.h"
#endif

/* ESP-IDF */
#include "grpc_client.hpp"
#include "esp_wifi.h"
#include "esp_netif.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "esp_system.h"
#include "esp_random.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <inttypes.h>
#include <time.h>
#include <sys/time.h>

static const char *TAG = "server_comm";

/* ── Configuration ─────────────────────────────────────────────────────────── */
#define COMM_TASK_STACK_SIZE    10240   /* nghttp2 session requires larger stack */
#define COMM_TASK_PRIORITY      2       /* Below heartbeat(3) and credential_poll(4) */
#define COMM_QUEUE_LENGTH       8       /* Pending events waiting for I/O */

/* ── Module state ──────────────────────────────────────────────────────────── */
static QueueHandle_t  s_comm_queue    = NULL;
static TaskHandle_t   s_comm_task     = NULL;
static bool           s_initialized   = false;
static bool           s_reader_degraded = false; /* set by EVENT_CREDENTIAL_READ_ERROR, cleared by RECOVERED */
static bool           s_clock_synced    = false; /* true after first successful settimeofday() from heartbeat */

/* gRPC client handle — persistent HTTP/2+TLS connection to the server. */
static grpc_client_handle_t s_grpc_handle = NULL;

/* Deployment config stored at init from NVS, used across the lifetime of the task */
static char     s_module_id[PORTUNUS_NVS_MODULE_ID_LEN];
static char     s_server_host[PORTUNUS_NVS_SERVER_HOST_LEN];
static uint16_t s_grpc_port;
#if PORTUNUS_HMAC_ENABLED
static char   s_hmac_secret[PORTUNUS_NVS_HMAC_SECRET_LEN];
static size_t s_hmac_secret_len;
#endif
/* Idle-tick counter for keepalive PINGs (1 tick ≈ 1 s). */
static int s_idle_ticks = 0;
#define GRPC_PING_INTERVAL_TICKS 30

/* ── HMAC helper ───────────────────────────────────────────────────────────── */

#if PORTUNUS_HMAC_ENABLED
/**
 * @brief Compute HMAC-SHA256(PORTUNUS_HMAC_SECRET, data) and write the
 *        hex-encoded result (64 chars + NUL) into @p out_hex.
 *
 * @return true on success, false on mbedTLS error.
 */
static bool compute_hmac_hex(const uint8_t *data, size_t data_len,
                              char out_hex[PORTUNUS_HMAC_HEX_LEN])
{
    const char  *secret     = s_hmac_secret;
    const size_t secret_len = s_hmac_secret_len;

    uint8_t raw[32]; /* SHA-256 output is 32 bytes */

    const mbedtls_md_info_t *info = mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);
    if (!info) { return false; }

    int rc = mbedtls_md_hmac(info,
                              (const unsigned char *)secret, secret_len,
                              data, data_len,
                              raw);
    if (rc != 0) {
        ESP_LOGE(TAG, "mbedtls_md_hmac failed: -0x%04x", (unsigned)(-rc));
        return false;
    }

    /* Hex-encode into out_hex */
    static const char hex_chars[] = "0123456789abcdef";
    for (int i = 0; i < 32; ++i) {
        out_hex[i * 2]     = hex_chars[(raw[i] >> 4) & 0x0F];
        out_hex[i * 2 + 1] = hex_chars[ raw[i]       & 0x0F];
    }
    out_hex[64] = '\0';
    return true;
}
/**
 * @brief Constant-time comparison of two 64-char hex HMAC strings.
 *
 * Runs all 64 iterations regardless of the first mismatch to avoid
 * leaking timing information about partial matches.
 */
static bool sig_hex_equal(const char *a, const char *b)
{
    uint8_t diff = 0;
    for (int i = 0; i < 64; ++i) {
        diff |= static_cast<uint8_t>(a[i]) ^ static_cast<uint8_t>(b[i]);
    }
    return diff == 0;
}
#endif /* PORTUNUS_HMAC_ENABLED */

/* ── Forward declarations ──────────────────────────────────────────────────── */
static void comm_task(void *arg);
static void handle_heartbeat(const event_heartbeat_t *hb);
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
static void handle_credential(const event_credential_read_t *cred);
#endif
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
static void handle_provision(const event_provision_request_t *req);
#endif

/* ── Helpers ───────────────────────────────────────────────────────────────── */

/**
 * @brief Get the station IP as a dotted-quad string.
 *        Returns false if the interface is down or has no IP.
 */
static bool get_sta_ip_str(char *buf, size_t len)
{
    esp_netif_t *netif = esp_netif_get_handle_from_ifkey("WIFI_STA_DEF");
    if (netif == NULL) { return false; }

    esp_netif_ip_info_t info;
    if (esp_netif_get_ip_info(netif, &info) != ESP_OK) { return false; }
    if (info.ip.addr == 0) { return false; }

    snprintf(buf, len, IPSTR, IP2STR(&info.ip));
    return true;
}

/**
 * @brief Get WiFi RSSI.  Returns false if unavailable.
 */
static bool get_rssi(int32_t *out)
{
    wifi_ap_record_t ap;
    if (esp_wifi_sta_get_ap_info(&ap) != ESP_OK) { return false; }
    *out = ap.rssi;
    return true;
}

/* ── Clock sync helpers ────────────────────────────────────────────────────── */

/**
 * @brief Parse an RFC 3339 UTC timestamp into a struct timeval.
 *
 * Accepts the format produced by the Go server: "2006-01-02T15:04:05.999999999Z".
 * Fractional seconds are optional; the 'Z' suffix is assumed (UTC).
 * Requires the process timezone to be set to UTC0 (done in server_comm_init).
 *
 * @return true on success, false if @p s is empty or malformed.
 */
static bool parse_server_time(const char *s, struct timeval *out)
{
    if (s == NULL || s[0] == '\0') { return false; }

    int year, mon, mday, hour, min, sec;
    if (sscanf(s, "%4d-%2d-%2dT%2d:%2d:%2d",
               &year, &mon, &mday, &hour, &min, &sec) < 6) {
        return false;
    }

    struct tm tm = {};
    tm.tm_year  = year - 1900;
    tm.tm_mon   = mon - 1;
    tm.tm_mday  = mday;
    tm.tm_hour  = hour;
    tm.tm_min   = min;
    tm.tm_sec   = sec;
    tm.tm_isdst = 0;

    /* TZ=UTC0 ensures mktime() treats this as UTC, not local time. */
    time_t t = mktime(&tm);
    if (t == (time_t)-1) { return false; }

    /* Parse fractional seconds (e.g. ".123456789") → microseconds. */
    long usec = 0;
    const char *dot = strchr(s, '.');
    if (dot != NULL) {
        /* Copy up to 9 digits, right-pad with '0' to get nanoseconds. */
        char frac[10] = {'0','0','0','0','0','0','0','0','0','\0'};
        int i = 0;
        const char *p = dot + 1;
        while (i < 9 && *p >= '0' && *p <= '9') { frac[i++] = *p++; }
        usec = strtol(frac, NULL, 10) / 1000;  /* ns → µs */
    }

    out->tv_sec  = t;
    out->tv_usec = (suseconds_t)usec;
    return true;
}

/**
 * @brief Set the system clock from a heartbeat response server_time field.
 *
 * Applies an RTT/2 correction: the server captures server_time before the
 * response travels back, so we add half the observed round-trip to center
 * the synchronisation error.  On a LAN the residual error is sub-millisecond.
 *
 * Sets s_clock_synced = true on success so that handle_credential() can
 * populate AccessRequest.requested_at for replay protection (phase 2).
 *
 * @param server_time  NUL-terminated RFC 3339 string from HeartbeatResponse.
 * @param rtt_us       Round-trip time of the heartbeat RPC in microseconds.
 */
static void sync_clock_from_response(const char *server_time, int64_t rtt_us)
{
    struct timeval tv;
    if (!parse_server_time(server_time, &tv)) {
        ESP_LOGW(TAG, "Clock sync skipped — unparseable server_time");
        return;
    }

    /* Apply RTT/2 offset, carrying microseconds into seconds if needed. */
    int64_t half_rtt_us = rtt_us / 2;
    tv.tv_usec += (suseconds_t)(half_rtt_us % 1000000LL);
    tv.tv_sec  += (time_t)(half_rtt_us / 1000000LL);
    if (tv.tv_usec >= 1000000L) {
        tv.tv_sec  += 1;
        tv.tv_usec -= 1000000L;
    }

    if (settimeofday(&tv, NULL) != 0) {
        ESP_LOGW(TAG, "Clock sync failed — settimeofday error");
        return;
    }

    s_clock_synced = true;
    ESP_LOGI(TAG, "Clock synced — server_time=%s rtt=%" PRId64 "us", server_time, rtt_us);
}

/* ── Transport helpers ─────────────────────────────────────────────────────── */

/**
 * @brief Perform a gRPC unary call with HMAC signing.
 *
 * Wraps grpc_client_unary_call() with HMAC metadata attachment.
 * The HMAC is computed over @p sig_projection — a canonical string built
 * from key request fields — and sent as a custom gRPC metadata header
 * (x-portunus-sig).  The server interceptor validates the same projection,
 * making verification independent of wire-format differences between Nanopb
 * and the Go protobuf library.
 *
 * Projection formats (must match hmacProjection() in grpcapi/interceptors.go):
 *   Heartbeat:   "heartbeat|{module_id}|{sequence}"
 *   Access:      "access|{module_id}|{credential_id}"
 *   Provision:   "provision|{module_id}|{hex(credential_uid)}"
 *
 * @param method         gRPC method path (e.g. "/portunus.v1.PortunusService/SendHeartbeat")
 * @param req_buf        Nanopb-encoded protobuf request body
 * @param req_len        Length of req_buf
 * @param sig_projection NUL-terminated canonical string to sign for HMAC
 * @param resp_buf       Buffer to receive the protobuf response
 * @param resp_cap       Capacity of resp_buf
 * @param resp_len       [out] Actual protobuf bytes written to resp_buf
 * @param grpc_status    [out] gRPC status code (0 = OK)
 * @param out_sig_hex    [out] If non-NULL, receives the x-portunus-sig trailer
 *                       from the server response (PORTUNUS_HMAC_HEX_LEN bytes).
 *                       Pass NULL for RPCs that do not need response verification.
 *
 * @return PORTUNUS_OK on successful round-trip.
 */
static portunus_err_t grpc_post_proto(const char *method,
                                       const uint8_t *req_buf, size_t req_len,
                                       const char *sig_projection,
                                       uint8_t *resp_buf, size_t resp_cap,
                                       int *resp_len, int *grpc_status,
                                       char *out_sig_hex)
{
#if PORTUNUS_HMAC_ENABLED
    /* Sign the canonical projection string, not the raw protobuf bytes.
     * The server interceptor computes the same projection from parsed fields,
     * so both sides agree even when Nanopb and Go encode the same message
     * with different field ordering or varint padding. */
    char sig_hex[PORTUNUS_HMAC_HEX_LEN];
    if (compute_hmac_hex((const uint8_t *)sig_projection, strlen(sig_projection), sig_hex)) {
        grpc_client_set_metadata(s_grpc_handle, PORTUNUS_HMAC_HEADER_NAME, sig_hex);
    } else {
        ESP_LOGE(TAG, "HMAC computation failed — aborting RPC");
        return PORTUNUS_ERR_HTTP_CONNECT;
    }
#else
    (void)sig_projection;
#endif /* PORTUNUS_HMAC_ENABLED */

    return grpc_client_unary_call(s_grpc_handle, method,
                                  req_buf, req_len,
                                  resp_buf, resp_cap,
                                  resp_len, grpc_status,
                                  out_sig_hex);
}

/* ── Event bus subscriber callbacks ────────────────────────────────────────── */
/* These run on the event bus dispatcher task and must be non-blocking.
   They simply copy the event into the server_comm queue. */

static void on_heartbeat_event(const portunus_event_t *event, void *ctx)
{
    (void)ctx;
    if (s_comm_queue == NULL) { return; }
    /* Best-effort: drop if queue is full rather than blocking dispatcher */
    xQueueSend(s_comm_queue, event, 0);
}

static void on_reader_fault_event(const portunus_event_t *event, void *ctx)
{
    (void)ctx;
    if (s_comm_queue == NULL) { return; }
    xQueueSend(s_comm_queue, event, 0);
}

#ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
static void on_credential_event(const portunus_event_t *event, void *ctx)
{
    (void)ctx;
    if (s_comm_queue == NULL) { return; }
    xQueueSend(s_comm_queue, event, 0);
}
#endif /* CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT */

#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
static void on_provision_event(const portunus_event_t *event, void *ctx)
{
    (void)ctx;
    if (s_comm_queue == NULL) { return; }
    xQueueSend(s_comm_queue, event, 0);
}
#endif

/* ── Event handlers (run on comm_task) ─────────────────────────────────────── */

/**
 * @brief Publish an EVENT_ACCESS_DENIED so the FSM can show error feedback.
 *
 * Called on every credential-path failure (no WiFi, HTTP error, bad
 * response, decode failure) so the user always sees a deny indication
 * rather than the CARD_READ LED stuck on indefinitely.
 *
 * @param credential_id  FNV-1a log fingerprint of the credential (never raw UID).
 * @param reason         Short reason string for logs / audit trail.
 */
static void publish_access_denied(const char *credential_id, const char *reason)
{
    portunus_event_t deny;
    memset(&deny, 0, sizeof(deny));
    deny.id = EVENT_ACCESS_DENIED;

    if (credential_id != NULL) {
        strncpy(deny.payload.access_decision.credential_id, credential_id,
                sizeof(deny.payload.access_decision.credential_id) - 1);
    }
    strncpy(deny.payload.access_decision.reason, reason,
            sizeof(deny.payload.access_decision.reason) - 1);
    deny.payload.access_decision.granted = false;
    deny.payload.access_decision.known   = false;

    event_bus_publish(&deny);
}

static void handle_heartbeat(const event_heartbeat_t *hb)
{
    /* Build protobuf request */
    portunus_v1_HeartbeatRequest req = portunus_v1_HeartbeatRequest_init_zero;

    strncpy(req.module_id, s_module_id, sizeof(req.module_id) - 1);
    strncpy(req.firmware_version, PORTUNUS_FW_VERSION, sizeof(req.firmware_version) - 1);
    req.uptime_s        = hb->uptime_sec;
    req.free_heap_bytes = hb->free_heap_bytes;
    req.sequence        = hb->sequence;

    if (get_sta_ip_str(req.ip, sizeof(req.ip))) {
        /* ip populated */
    }

    int32_t rssi;
    if (get_rssi(&rssi)) {
        req.has_rssi_dbm = true;
        req.rssi_dbm     = rssi;
    }

    /* Encode */
    uint8_t req_buf[portunus_v1_HeartbeatRequest_size];
    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));
    if (!pb_encode(&ostream, portunus_v1_HeartbeatRequest_fields, &req)) {
        ESP_LOGE(TAG, "Heartbeat encode failed: %s", PB_GET_ERROR(&ostream));
        return;
    }

    /* POST */
    uint8_t resp_buf[portunus_v1_HeartbeatResponse_size + 16];  /* small margin */
    int resp_len = 0;
    int64_t t_before = esp_timer_get_time();

    char proj[128];
    snprintf(proj, sizeof(proj), "heartbeat|%s|%" PRIu32, req.module_id, req.sequence);
    int grpc_status = 0;
    portunus_err_t err = grpc_post_proto(
        "/portunus.v1.PortunusService/SendHeartbeat",
        req_buf, ostream.bytes_written,
        proj,
        resp_buf, sizeof(resp_buf),
        &resp_len, &grpc_status, nullptr);
    if (err != PORTUNUS_OK) {
        ESP_LOGW(TAG, "Heartbeat gRPC failed: err=0x%04x", (unsigned)err);
        return;
    }
    if (grpc_status != GRPC_STATUS_OK) {
        ESP_LOGW(TAG, "Heartbeat gRPC status: %d", grpc_status);
        return;
    }

    /* Decode response */
    portunus_v1_HeartbeatResponse resp = portunus_v1_HeartbeatResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(resp_buf, (size_t)resp_len);
    if (!pb_decode(&istream, portunus_v1_HeartbeatResponse_fields, &resp)) {
        ESP_LOGW(TAG, "Heartbeat decode failed: %s", PB_GET_ERROR(&istream));
        return;
    }

    int64_t rtt_us = esp_timer_get_time() - t_before;
    sync_clock_from_response(resp.server_time, rtt_us);

    if (s_reader_degraded) {
        ESP_LOGW(TAG, "Heartbeat OK — known=%d clock_synced=%d [READER DEGRADED]",
                 resp.known, s_clock_synced);
    } else {
        ESP_LOGI(TAG, "Heartbeat OK — known=%d clock_synced=%d",
                 resp.known, s_clock_synced);
    }
}

#ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
static void handle_credential(const event_credential_read_t *cred)
{
    /* Build protobuf request */
    portunus_v1_AccessRequest req = portunus_v1_AccessRequest_init_zero;

    strncpy(req.module_id, s_module_id, sizeof(req.module_id) - 1);
    credential_uid_to_hex(&cred->credential, req.credential_id, sizeof(req.credential_id));

    char req_log_id[CREDENTIAL_LOG_ID_LEN];
    credential_uid_to_log_id(&cred->credential, req_log_id, sizeof(req_log_id));

    /* Replay protection: fill nonce with 16 cryptographically random bytes. */
    req.nonce.size = 16;
    esp_fill_random(req.nonce.bytes, req.nonce.size);

    /* Replay protection: populate requested_at when the clock is synced. */
    if (s_clock_synced) {
        struct timeval tv;
        gettimeofday(&tv, NULL);
        struct tm tm_utc;
        gmtime_r(&tv.tv_sec, &tm_utc);
        /* Format: "2006-01-02T15:04:05.000000Z" (microsecond precision) */
        int n = strftime(req.requested_at, sizeof(req.requested_at) - 1,
                         "%Y-%m-%dT%H:%M:%S", &tm_utc);
        if (n > 0) {
            snprintf(req.requested_at + n, sizeof(req.requested_at) - n,
                     ".%06ldZ", (long)tv.tv_usec);
        }
    }

    /* Encode */
    uint8_t req_buf[portunus_v1_AccessRequest_size];
    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));
    if (!pb_encode(&ostream, portunus_v1_AccessRequest_fields, &req)) {
        ESP_LOGE(TAG, "Access encode failed: %s", PB_GET_ERROR(&ostream));
        publish_access_denied(req_log_id, "encode_error");
        return;
    }

    /* POST */
    uint8_t resp_buf[portunus_v1_AccessResponse_size + 16];
    int resp_len = 0;
#if PORTUNUS_HMAC_ENABLED
    char resp_sig_hex[PORTUNUS_HMAC_HEX_LEN] = {};
    char *p_resp_sig = resp_sig_hex;
#else
    char *p_resp_sig = nullptr;
#endif

    /* Hex-encode nonce for the HMAC projection.
     * Format: "access|{module_id}|{credential_id}|{nonce_hex}|{requested_at}"
     * Must match hmacProjection() in grpcapi/interceptors.go. */
    char nonce_hex[33] = {};
    for (size_t i = 0; i < req.nonce.size && i * 2 + 2 < sizeof(nonce_hex); ++i) {
        snprintf(&nonce_hex[i * 2], 3, "%02x",
                 static_cast<unsigned>(req.nonce.bytes[i]));
    }
    char proj[192];
    snprintf(proj, sizeof(proj), "access|%s|%s|%s|%s",
             req.module_id, req.credential_id, nonce_hex, req.requested_at);
    int grpc_status = 0;
    portunus_err_t err = grpc_post_proto(
        "/portunus.v1.PortunusService/RequestAccess",
        req_buf, ostream.bytes_written,
        proj,
        resp_buf, sizeof(resp_buf),
        &resp_len, &grpc_status, p_resp_sig);
    if (err != PORTUNUS_OK) {
        ESP_LOGW(TAG, "Access gRPC failed: err=0x%04x", (unsigned)err);
        publish_access_denied(req_log_id, "grpc_error");
        return;
    }
    if (grpc_status != GRPC_STATUS_OK) {
        ESP_LOGW(TAG, "Access gRPC status: %d", grpc_status);
        publish_access_denied(req_log_id, "grpc_status_error");
        return;
    }

    /* Decode response */
    portunus_v1_AccessResponse resp = portunus_v1_AccessResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(resp_buf, (size_t)resp_len);
    if (!pb_decode(&istream, portunus_v1_AccessResponse_fields, &resp)) {
        ESP_LOGW(TAG, "Access decode failed: %s", PB_GET_ERROR(&istream));
        publish_access_denied(req_log_id, "decode_error");
        return;
    }

#if PORTUNUS_HMAC_ENABLED
    /* Verify the server's response signature before acting on the decision.
     * Projection: "access|{module_id}|{credential_id}|{0 or 1}" — must match
     * AccessResponseProjection() in server/internal/grpcapi/interceptors.go. */
    if (resp_sig_hex[0] == '\0') {
        ESP_LOGE(TAG, "Access response missing X-Portunus-Sig — denying");
        publish_access_denied(req_log_id, "missing_response_sig");
        return;
    }
    char resp_proj[128];
    snprintf(resp_proj, sizeof(resp_proj), "access|%s|%s|%d",
             req.module_id, req.credential_id, resp.granted ? 1 : 0);
    char expected_sig[PORTUNUS_HMAC_HEX_LEN];
    if (!compute_hmac_hex((const uint8_t *)resp_proj, strlen(resp_proj), expected_sig)) {
        ESP_LOGE(TAG, "HMAC compute failed during response verify");
        publish_access_denied(req_log_id, "sig_compute_error");
        return;
    }
    if (!sig_hex_equal(resp_sig_hex, expected_sig)) {
        ESP_LOGE(TAG, "Access response HMAC mismatch — denying");
        publish_access_denied(req_log_id, "invalid_response_sig");
        return;
    }
#endif /* PORTUNUS_HMAC_ENABLED */

    ESP_LOGI(TAG, "Access decision — id=%s granted=%d reason=%s known=%d",
             req_log_id, resp.granted, resp.reason, resp.known);

    /* Publish decision event back to the bus */
    portunus_event_t decision;
    memset(&decision, 0, sizeof(decision));
    decision.id = resp.granted ? EVENT_ACCESS_GRANTED : EVENT_ACCESS_DENIED;

    strncpy(decision.payload.access_decision.credential_id, req_log_id,
            sizeof(decision.payload.access_decision.credential_id) - 1);
    strncpy(decision.payload.access_decision.reason, resp.reason,
            sizeof(decision.payload.access_decision.reason) - 1);
    decision.payload.access_decision.granted = resp.granted;
    decision.payload.access_decision.known   = resp.known;

    event_bus_publish(&decision);
}
#endif /* CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT */

/* ── Provisioning handler (PROVISIONING_CONSOLE only) ──────────────────────── */

#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE

static void publish_provision_result(provision_result_reason_t reason,
                                     const char *member_uuid,
                                     const char *detail)
{
    portunus_event_t evt;
    memset(&evt, 0, sizeof(evt));
    evt.id = (reason == PROVISION_RESULT_PENDING_CREATED)
             ? EVENT_PROVISION_SUCCESS
             : EVENT_PROVISION_FAILED;

    if (member_uuid) {
        strncpy(evt.payload.provision_result.member_uuid, member_uuid,
                sizeof(evt.payload.provision_result.member_uuid) - 1);
    }
    evt.payload.provision_result.reason = reason;
    if (detail) {
        strncpy(evt.payload.provision_result.detail, detail,
                sizeof(evt.payload.provision_result.detail) - 1);
    }
    event_bus_publish(&evt);
}

static void handle_provision(const event_provision_request_t *req)
{
    /* Build ProvisionCredentialRequest (capture path only). */
    portunus_v1_ProvisionCredentialRequest pb_req =
        portunus_v1_ProvisionCredentialRequest_init_zero;

    strncpy(pb_req.module_id, s_module_id,
            sizeof(pb_req.module_id) - 1);

    /* New member card UID — server applies HMAC-SHA256 before storing. */
    size_t uid_n = req->credential_uid_len;
    if (uid_n > sizeof(pb_req.credential_uid.bytes)) {
        uid_n = sizeof(pb_req.credential_uid.bytes);
    }
    pb_req.credential_uid.size = (pb_size_t)uid_n;
    memcpy(pb_req.credential_uid.bytes, req->credential_uid, uid_n);

    /* Encode */
    uint8_t req_buf[portunus_v1_ProvisionCredentialRequest_size];
    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));
    if (!pb_encode(&ostream, portunus_v1_ProvisionCredentialRequest_fields, &pb_req)) {
        ESP_LOGE(TAG, "Provision encode failed: %s", PB_GET_ERROR(&ostream));
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "encode_error");
        return;
    }

    /* Send */
    uint8_t resp_buf[portunus_v1_ProvisionCredentialResponse_size + 16];
    int resp_len = 0;

    /* Hex-encode credential_uid for the HMAC projection.
     * Must match hmacProjection() in grpcapi/interceptors.go. */
    char uid_hex[64] = {};
    for (size_t i = 0;
         i < pb_req.credential_uid.size && i * 2 + 2 < sizeof(uid_hex);
         ++i) {
        snprintf(&uid_hex[i * 2], 3, "%02x",
                 static_cast<unsigned>(pb_req.credential_uid.bytes[i]));
    }
    char proj[128];
    snprintf(proj, sizeof(proj), "provision|%s|%s", pb_req.module_id, uid_hex);
    int grpc_status = 0;
    portunus_err_t err = grpc_post_proto(
        "/portunus.v1.PortunusService/ProvisionCredential",
        req_buf, ostream.bytes_written,
        proj,
        resp_buf, sizeof(resp_buf),
        &resp_len, &grpc_status, nullptr);
    if (err != PORTUNUS_OK) {
        ESP_LOGW(TAG, "Provision gRPC failed: 0x%04x", (unsigned)err);
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "grpc_error");
        return;
    }
    if (grpc_status != GRPC_STATUS_OK) {
        ESP_LOGW(TAG, "Provision gRPC status: %d", grpc_status);
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "grpc_status_error");
        return;
    }

    /* Decode response */
    portunus_v1_ProvisionCredentialResponse pb_resp =
        portunus_v1_ProvisionCredentialResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(resp_buf, (size_t)resp_len);
    if (!pb_decode(&istream, portunus_v1_ProvisionCredentialResponse_fields, &pb_resp)) {
        ESP_LOGW(TAG, "Provision decode failed: %s", PB_GET_ERROR(&istream));
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "decode_error");
        return;
    }

    ESP_LOGI(TAG, "Provision response — status=%d member_uuid=%s detail=%s",
             pb_resp.status, pb_resp.member_uuid, pb_resp.detail);

    /* Map proto status → internal reason code */
    provision_result_reason_t reason;
    switch (pb_resp.status) {
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_PENDING_CREATED:
        reason = PROVISION_RESULT_PENDING_CREATED;    break;
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_DUPLICATE_ACTIVE:
        reason = PROVISION_RESULT_DUPLICATE_ACTIVE;   break;
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_DUPLICATE_INACTIVE:
        reason = PROVISION_RESULT_DUPLICATE_INACTIVE; break;
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_DUPLICATE_PENDING:
        reason = PROVISION_RESULT_DUPLICATE_PENDING;  break;
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_UNAUTHORIZED:
        reason = PROVISION_RESULT_UNAUTHORIZED;       break;
    default:
        reason = PROVISION_RESULT_COMM_ERROR;         break;
    }

    publish_provision_result(reason, pb_resp.member_uuid, pb_resp.detail);
}

#endif /* CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE */

/* ── Task ──────────────────────────────────────────────────────────────────── */

static void comm_task(void *arg)
{
    (void)arg;
    portunus_event_t event;

    ESP_LOGI(TAG, "Server comm task started");

    for (;;) {
        if (xQueueReceive(s_comm_queue, &event, pdMS_TO_TICKS(1000)) != pdTRUE) {
            if (++s_idle_ticks >= GRPC_PING_INTERVAL_TICKS) {
                s_idle_ticks = 0;
                if (s_grpc_handle != NULL && grpc_client_is_connected(s_grpc_handle)) {
                    portunus_err_t perr = grpc_client_send_ping(s_grpc_handle);
                    if (perr != PORTUNUS_OK) {
                        ESP_LOGW(TAG, "keepalive PING failed: 0x%04x", (unsigned)perr);
                    }
                }
            }
            continue;   /* Idle tick — nothing queued */
        }

        s_idle_ticks = 0;  /* Reset on any RPC activity */

        if (!wifi_mgr_is_connected()) {
            ESP_LOGD(TAG, "WiFi not connected — dropping event 0x%04x",
                     (unsigned)event.id);

            /* Credential events need a deny so the FSM clears CARD_READ
               feedback.  Heartbeats can be silently dropped. */
            if (event.id == EVENT_CREDENTIAL_READ) {
                char log_id[CREDENTIAL_LOG_ID_LEN];
                credential_uid_to_log_id(&event.payload.credential_read.credential,
                                         log_id, sizeof(log_id));
                publish_access_denied(log_id, "no_network");
            }
            continue;
        }

        switch (event.id) {
        case EVENT_HEARTBEAT:
            handle_heartbeat(&event.payload.heartbeat);
            break;
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
        case EVENT_CREDENTIAL_READ:
            handle_credential(&event.payload.credential_read);
            break;
#endif
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
        case EVENT_PROVISION_REQUEST:
            handle_provision(&event.payload.provision_request);
            break;
#endif
        case EVENT_CREDENTIAL_READ_ERROR:
            s_reader_degraded = true;
            ESP_LOGW(TAG, "Credential reader degraded — heartbeats will reflect fault");
            break;
        case EVENT_CREDENTIAL_READER_RECOVERED:
            s_reader_degraded = false;
            ESP_LOGI(TAG, "Credential reader recovered — heartbeats nominal");
            break;
        default:
            ESP_LOGW(TAG, "Unexpected event 0x%04x in comm queue",
                     (unsigned)event.id);
            break;
        }
    }
}

/* ── Public API ────────────────────────────────────────────────────────────── */

bool server_comm_clock_synced(void)
{
    return s_clock_synced;
}

portunus_err_t server_comm_init(const portunus_device_config_t *cfg)
{
    if (s_initialized) {
        ESP_LOGW(TAG, "server_comm already initialised");
        return PORTUNUS_ERR_ALREADY_INIT;
    }

    strlcpy(s_module_id,   cfg->module_id,   sizeof(s_module_id));
    strlcpy(s_server_host, cfg->server_host, sizeof(s_server_host));
    s_grpc_port = cfg->grpc_port;

#if PORTUNUS_HMAC_ENABLED
    strlcpy(s_hmac_secret, cfg->hmac_secret, sizeof(s_hmac_secret));
    s_hmac_secret_len = strlen(cfg->hmac_secret);
    if (s_hmac_secret_len == 0) {
        ESP_LOGE(TAG, "HMAC is enabled but hmac_secret is empty in NVS");
        return PORTUNUS_FAIL;
    }
#endif

    /* Configure gRPC client (HTTP/2 + TLS). */
    {
        grpc_client_config_t grpc_cfg = {};
        grpc_cfg.host               = s_server_host;
        grpc_cfg.port               = s_grpc_port;
        grpc_cfg.connect_timeout_ms = PORTUNUS_SERVER_REQUEST_TIMEOUT_MS;
        grpc_cfg.rpc_timeout_ms     = PORTUNUS_SERVER_REQUEST_TIMEOUT_MS;
        grpc_cfg.skip_cert_verify   = PORTUNUS_TLS_SKIP_VERIFY;

      #if PORTUNUS_TLS_USE_CUSTOM_CA
        grpc_cfg.ca_cert_pem = ca_cert_pem_start;
      #else
        grpc_cfg.ca_cert_pem = NULL; /* Use ESP-IDF cert bundle */
      #endif

        portunus_err_t grpc_err = grpc_client_init(&grpc_cfg, &s_grpc_handle);
        if (grpc_err != PORTUNUS_OK) {
            ESP_LOGE(TAG, "gRPC client init failed: 0x%04x", (unsigned)grpc_err);
            return grpc_err;
        }
        ESP_LOGI(TAG, "Transport: gRPC (HTTP/2+TLS) → %s:%d",
                 s_server_host, (int)s_grpc_port);
    }

    /* Clock: operate in UTC so mktime() in parse_server_time() is correct. */
    setenv("TZ", "UTC0", 1);
    tzset();

    /* Create internal queue */
    s_comm_queue = xQueueCreate(COMM_QUEUE_LENGTH, sizeof(portunus_event_t));
    if (s_comm_queue == NULL) {
        ESP_LOGE(TAG, "Failed to create comm queue");
        return PORTUNUS_ERR_QUEUE_CREATE;
    }

    /* Subscribe to events */
    portunus_err_t sub_err;

    sub_err = event_bus_subscribe(EVENT_HEARTBEAT, on_heartbeat_event, NULL);
    if (sub_err != PORTUNUS_OK) {
        ESP_LOGE(TAG, "Failed to subscribe to heartbeat events: 0x%04x", (unsigned)sub_err);
    }

    sub_err = event_bus_subscribe(EVENT_CREDENTIAL_READ_ERROR, on_reader_fault_event, NULL);
    if (sub_err != PORTUNUS_OK) {
        ESP_LOGE(TAG, "Failed to subscribe to reader error events: 0x%04x", (unsigned)sub_err);
    }

    sub_err = event_bus_subscribe(EVENT_CREDENTIAL_READER_RECOVERED, on_reader_fault_event, NULL);
    if (sub_err != PORTUNUS_OK) {
        ESP_LOGE(TAG, "Failed to subscribe to reader recovery events: 0x%04x", (unsigned)sub_err);
    }

#ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
    sub_err = event_bus_subscribe(EVENT_CREDENTIAL_READ, on_credential_event, NULL);
    if (sub_err != PORTUNUS_OK) {
        ESP_LOGE(TAG, "Failed to subscribe to credential events: 0x%04x", (unsigned)sub_err);
    }
#endif
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
    sub_err = event_bus_subscribe(EVENT_PROVISION_REQUEST, on_provision_event, NULL);
    if (sub_err != PORTUNUS_OK) {
        ESP_LOGE(TAG, "Failed to subscribe to provision events: 0x%04x", (unsigned)sub_err);
    }
#endif

    /* Start task */
    BaseType_t ret = xTaskCreate(
        comm_task,
        "server_comm",
        COMM_TASK_STACK_SIZE,
        NULL,
        COMM_TASK_PRIORITY,
        &s_comm_task
    );
    if (ret != pdPASS) {
        ESP_LOGE(TAG, "Failed to create comm task");
        return PORTUNUS_ERR_TASK_CREATE;
    }

    s_initialized = true;
    ESP_LOGI(TAG, "Server comm initialised");
    return PORTUNUS_OK;
}

void server_comm_deinit(void)
{
    if (!s_initialized) {
        return;
    }

    /* Delete the network task first so it stops pulling from the queue. */
    if (s_comm_task != NULL) {
        vTaskDelete(s_comm_task);
        s_comm_task = NULL;
    }

    /* Drain and delete the internal queue. */
    if (s_comm_queue != NULL) {
        portunus_event_t discarded;
        while (xQueueReceive(s_comm_queue, &discarded, 0) == pdTRUE) {
            /* discard */
        }
        vQueueDelete(s_comm_queue);
        s_comm_queue = NULL;
    }

    /* Destroy the gRPC client (closes TLS + HTTP/2 session). */
    if (s_grpc_handle != NULL) {
        grpc_client_destroy(s_grpc_handle);
        s_grpc_handle = NULL;
    }

    s_initialized = false;
    ESP_LOGI(TAG, "Server comm deinitialised");
}