/**
 * @file server_comm.cpp
 * @brief Server communication component implementation.
 *
 * Architecture:
 *   Event bus callbacks (on_heartbeat_event / on_credential_event) copy
 *   incoming events into s_comm_queue.  The comm_task drains the queue,
 *   encodes protobuf, performs the HTTP POST, and publishes the result
 *   (access decisions) back to the event bus.
 *
 *   HTTP I/O is blocking and runs entirely on the comm_task stack, so
 *   the event bus dispatcher is never blocked.
 */

#include "server_comm.h"
#include "event_bus.h"
#include "event_types.h"
#include "error_codes.h"
#include "network_config.h"
#include "security_config.h"
#include "wifi_mgr.h"
#include "portunus_types.h"
#include "credential_types.h"

/* Nanopb */
#include "portunus/v1/portunus.pb.h"
#include <pb_encode.h>
#include <pb_decode.h>

/* Provisioning: SHA-256 via mbedTLS (always available when mbedtls is linked) */
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
  #include "mbedtls/sha256.h"
#endif

/* TLS / HMAC */
#if PORTUNUS_USE_TLS
  #if PORTUNUS_TLS_USE_CUSTOM_CA
    /* Embedded CA certificate for LAN TLS pinning.
     * The PEM is compiled into the binary by EMBED_TXTFILES in CMakeLists.txt.
     * Generated by: ./scripts/generate_certs.sh --ip <SERVER_IP> */
    extern const char ca_cert_pem_start[] asm("_binary_ca_cert_pem_start");
    extern const char ca_cert_pem_end[]   asm("_binary_ca_cert_pem_end");
  #else
    #include "esp_crt_bundle.h"
  #endif
#endif
#if PORTUNUS_HMAC_ENABLED
  #include "mbedtls/md.h"
#endif

/* ESP-IDF */
#if !PORTUNUS_USE_GRPC
  #include "esp_http_client.h"
#else
  #include "grpc_client.h"
#endif
#include "esp_wifi.h"
#include "esp_netif.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "esp_system.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#include <string.h>
#include <stdio.h>
#include <inttypes.h>

static const char *TAG = "server_comm";

/* ── Configuration ─────────────────────────────────────────────────────────── */
#if PORTUNUS_USE_GRPC
  #define COMM_TASK_STACK_SIZE    10240     /* Larger stack for nghttp2 session */
#else
  #define COMM_TASK_STACK_SIZE    6144
#endif
#define COMM_TASK_PRIORITY      2       /* Below heartbeat(3) and credential_poll(4) */
#define COMM_QUEUE_LENGTH       8       /* Pending events waiting for HTTP I/O */
#define URL_MAX_LEN            128

/* ── Module state ──────────────────────────────────────────────────────────── */
static QueueHandle_t  s_comm_queue   = NULL;
static TaskHandle_t   s_comm_task    = NULL;
static bool           s_initialized  = false;

#if PORTUNUS_USE_GRPC
/* gRPC client handle — persistent HTTP/2+TLS connection to the server. */
static grpc_client_handle_t s_grpc_handle = NULL;
/* Idle-tick counter for keepalive PINGs (1 tick ≈ 1 s). */
static int s_idle_ticks = 0;
#define GRPC_PING_INTERVAL_TICKS 30
#else
/* Reusable URL buffers built once at init */
static char s_heartbeat_url[URL_MAX_LEN];
static char s_access_url[URL_MAX_LEN];
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
static char s_provision_url[URL_MAX_LEN];
#endif
#endif /* !PORTUNUS_USE_GRPC */

/* ── HMAC helper ───────────────────────────────────────────────────────────── */

#if PORTUNUS_HMAC_ENABLED
/**
 * @brief Compute HMAC-SHA256(PORTUNUS_HMAC_SECRET, data) and write the
 *        hex-encoded result (64 chars + NUL) into @p out_hex.
 *
 * @return true on success, false on mbedTLS error.
 */
static bool compute_hmac_hex(const uint8_t *data, size_t data_len,
                              char out_hex[PORTUNUS_HMAC_HEX_LEN])
{
    static const char *secret     = PORTUNUS_HMAC_SECRET;
    static const size_t secret_len = sizeof(PORTUNUS_HMAC_SECRET) - 1; /* strip NUL */

    uint8_t raw[32]; /* SHA-256 output is 32 bytes */

    const mbedtls_md_info_t *info = mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);
    if (!info) { return false; }

    int rc = mbedtls_md_hmac(info,
                              (const unsigned char *)secret, secret_len,
                              data, data_len,
                              raw);
    if (rc != 0) {
        ESP_LOGE(TAG, "mbedtls_md_hmac failed: -0x%04x", (unsigned)(-rc));
        return false;
    }

    /* Hex-encode into out_hex */
    static const char hex_chars[] = "0123456789abcdef";
    for (int i = 0; i < 32; ++i) {
        out_hex[i * 2]     = hex_chars[(raw[i] >> 4) & 0x0F];
        out_hex[i * 2 + 1] = hex_chars[ raw[i]       & 0x0F];
    }
    out_hex[64] = '\0';
    return true;
}
#endif /* PORTUNUS_HMAC_ENABLED */

/* ── Forward declarations ──────────────────────────────────────────────────── */
static void comm_task(void *arg);
static void handle_heartbeat(const event_heartbeat_t *hb);
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
static void handle_credential(const event_credential_read_t *cred);
#endif
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
static void handle_provision(const event_provision_request_t *req);
#endif

/* ── Helpers ───────────────────────────────────────────────────────────────── */

/**
 * @brief Get the station IP as a dotted-quad string.
 *        Returns false if the interface is down or has no IP.
 */
static bool get_sta_ip_str(char *buf, size_t len)
{
    esp_netif_t *netif = esp_netif_get_handle_from_ifkey("WIFI_STA_DEF");
    if (netif == NULL) { return false; }

    esp_netif_ip_info_t info;
    if (esp_netif_get_ip_info(netif, &info) != ESP_OK) { return false; }
    if (info.ip.addr == 0) { return false; }

    snprintf(buf, len, IPSTR, IP2STR(&info.ip));
    return true;
}

/**
 * @brief Get WiFi RSSI.  Returns false if unavailable.
 */
static bool get_rssi(int32_t *out)
{
    wifi_ap_record_t ap;
    if (esp_wifi_sta_get_ap_info(&ap) != ESP_OK) { return false; }
    *out = ap.rssi;
    return true;
}

/* ── Transport helpers ─────────────────────────────────────────────────────── */

#if PORTUNUS_USE_GRPC

/**
 * @brief Perform a gRPC unary call with HMAC signing.
 *
 * Wraps grpc_client_unary_call() with HMAC metadata attachment.
 * The HMAC is computed over the raw protobuf body (same as the HTTP path)
 * and sent as a custom gRPC metadata header (x-portunus-sig).
 *
 * @param method     gRPC method path (e.g. "/portunus.v1.PortunusService/SendHeartbeat")
 * @param req_buf    Nanopb-encoded protobuf request body
 * @param req_len    Length of req_buf
 * @param resp_buf   Buffer to receive the protobuf response
 * @param resp_cap   Capacity of resp_buf
 * @param resp_len   [out] Actual protobuf bytes written to resp_buf
 * @param grpc_status [out] gRPC status code (0 = OK)
 *
 * @return PORTUNUS_OK on successful round-trip.
 */
static portunus_err_t grpc_post_proto(const char *method,
                                       const uint8_t *req_buf, size_t req_len,
                                       uint8_t *resp_buf, size_t resp_cap,
                                       int *resp_len, int *grpc_status)
{
#if PORTUNUS_HMAC_ENABLED
    /* Compute HMAC-SHA256 over the protobuf body and set as gRPC metadata.
     * The server interceptor validates this before processing the RPC. */
    char sig_hex[PORTUNUS_HMAC_HEX_LEN];
    if (compute_hmac_hex(req_buf, req_len, sig_hex)) {
        grpc_client_set_metadata(s_grpc_handle, PORTUNUS_HMAC_HEADER_NAME, sig_hex);
    } else {
        ESP_LOGE(TAG, "HMAC computation failed — aborting RPC");
        return PORTUNUS_ERR_HTTP_CONNECT;
    }
#endif /* PORTUNUS_HMAC_ENABLED */

    return grpc_client_unary_call(s_grpc_handle, method,
                                  req_buf, req_len,
                                  resp_buf, resp_cap,
                                  resp_len, grpc_status);
}

#else /* !PORTUNUS_USE_GRPC — HTTP/1.1 path */

/**
 * @brief POST a protobuf-encoded buffer to url, read the response into
 *        resp_buf.
 *
 * Security hardening applied here:
 *   • Uses https:// when PORTUNUS_USE_TLS is set (Kconfig).
 *   • Validates the server certificate via the ESP-IDF Mozilla CA bundle
 *     unless PORTUNUS_TLS_SKIP_VERIFY is set (dev only).
 *   • Adds X-Portunus-Sig HMAC-SHA256 header when PORTUNUS_HMAC_ENABLED.
 *
 * @param url        Full URL (e.g. "https://192.168.1.100:8443/v1/heartbeat")
 * @param req_buf    Encoded protobuf request body
 * @param req_len    Length of req_buf
 * @param resp_buf   Buffer to receive the response body
 * @param resp_cap   Capacity of resp_buf
 * @param resp_len   [out] Actual bytes written to resp_buf
 * @param http_status [out] HTTP status code
 *
 * @return PORTUNUS_OK on successful round-trip (even if http_status != 200).
 */
static portunus_err_t http_post_proto(const char *url,
                                      const uint8_t *req_buf, size_t req_len,
                                      uint8_t *resp_buf, size_t resp_cap,
                                      int *resp_len, int *http_status)
{
    esp_http_client_config_t cfg = {};
    cfg.url         = url;
    cfg.timeout_ms  = PORTUNUS_SERVER_REQUEST_TIMEOUT_MS;
    cfg.disable_auto_redirect = true;

#if PORTUNUS_USE_TLS
  #if PORTUNUS_TLS_SKIP_VERIFY
    /* Dev override: accept any certificate (INSECURE). */
    cfg.skip_cert_common_name_check = true;
    cfg.crt_bundle_attach           = NULL;
    cfg.transport_type              = HTTP_TRANSPORT_OVER_SSL;
    ESP_LOGW(TAG, "TLS cert verification DISABLED (dev mode)");
  #elif PORTUNUS_TLS_USE_CUSTOM_CA
    /* LAN deployment: pin to the embedded private CA certificate.
     * The server cert must chain to this CA or the handshake will fail. */
    cfg.cert_pem        = ca_cert_pem_start;
    cfg.transport_type  = HTTP_TRANSPORT_OVER_SSL;
  #else
    /* Public CA: validate against the ESP-IDF Mozilla CA bundle
     * (covers Let's Encrypt, DigiCert, etc.). */
    cfg.crt_bundle_attach = esp_crt_bundle_attach;
  #endif
#endif /* PORTUNUS_USE_TLS */

    esp_http_client_handle_t client = esp_http_client_init(&cfg);
    if (client == NULL) {
        ESP_LOGE(TAG, "http_client_init failed");
        return PORTUNUS_ERR_HTTP_CONNECT;
    }

    esp_http_client_set_method(client, HTTP_METHOD_POST);
    esp_http_client_set_header(client, "Content-Type", "application/x-protobuf");

#if PORTUNUS_HMAC_ENABLED
    /* Compute HMAC-SHA256 over the request body and attach it as a header.
       The server verifies this before processing the message. */
    char sig_hex[PORTUNUS_HMAC_HEX_LEN];
    if (compute_hmac_hex(req_buf, req_len, sig_hex)) {
        esp_http_client_set_header(client, PORTUNUS_HMAC_HEADER_NAME, sig_hex);
    } else {
        ESP_LOGE(TAG, "HMAC computation failed — aborting request");
        esp_http_client_cleanup(client);
        return PORTUNUS_ERR_HTTP_CONNECT;
    }
#endif /* PORTUNUS_HMAC_ENABLED */

    esp_err_t err = esp_http_client_open(client, (int)req_len);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "HTTP open failed: %s", esp_err_to_name(err));
        esp_http_client_cleanup(client);
        return PORTUNUS_ERR_HTTP_CONNECT;
    }

    /* Write request body, handling partial writes */
    size_t total_written = 0;
    while (total_written < req_len) {
        int written = esp_http_client_write(client,
                                            (const char *)req_buf + total_written,
                                            (int)(req_len - total_written));
        if (written < 0) {
            ESP_LOGE(TAG, "HTTP write failed (wrote %zu / %zu)", total_written, req_len);
            esp_http_client_close(client);
            esp_http_client_cleanup(client);
            return PORTUNUS_ERR_HTTP_CONNECT;
        }
        total_written += (size_t)written;
    }

    int content_length = esp_http_client_fetch_headers(client);
    (void)content_length;  /* May be -1 for chunked; we read until done */

    *http_status = esp_http_client_get_status_code(client);

    int total_read = 0;
    int read_len;
    while ((read_len = esp_http_client_read(client,
                                            (char *)resp_buf + total_read,
                                            (int)(resp_cap - total_read))) > 0) {
        total_read += read_len;
        if ((size_t)total_read >= resp_cap) { break; }
    }
    *resp_len = total_read;

    esp_http_client_close(client);
    esp_http_client_cleanup(client);

    return PORTUNUS_OK;
}

#endif /* PORTUNUS_USE_GRPC */

/* ── Event bus subscriber callbacks ────────────────────────────────────────── */
/* These run on the event bus dispatcher task and must be non-blocking.
   They simply copy the event into the server_comm queue. */

static void on_heartbeat_event(const portunus_event_t *event, void *ctx)
{
    (void)ctx;
    if (s_comm_queue == NULL) { return; }
    /* Best-effort: drop if queue is full rather than blocking dispatcher */
    xQueueSend(s_comm_queue, event, 0);
}

static void on_credential_event(const portunus_event_t *event, void *ctx)
{
    (void)ctx;
    if (s_comm_queue == NULL) { return; }
    xQueueSend(s_comm_queue, event, 0);
}

#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
static void on_provision_event(const portunus_event_t *event, void *ctx)
{
    (void)ctx;
    if (s_comm_queue == NULL) { return; }
    xQueueSend(s_comm_queue, event, 0);
}
#endif

/* ── Event handlers (run on comm_task) ─────────────────────────────────────── */

/**
 * @brief Publish an EVENT_ACCESS_DENIED so the FSM can show error feedback.
 *
 * Called on every credential-path failure (no WiFi, HTTP error, bad
 * response, decode failure) so the user always sees a deny indication
 * rather than the CARD_READ LED stuck on indefinitely.
 *
 * @param credential_id  Hex-encoded credential UID (may be empty if unknown).
 * @param reason         Short reason string for logs / audit trail.
 */
static void publish_access_denied(const char *credential_id, const char *reason)
{
    portunus_event_t deny;
    memset(&deny, 0, sizeof(deny));
    deny.id = EVENT_ACCESS_DENIED;

    if (credential_id != NULL) {
        strncpy(deny.payload.access_decision.credential_id, credential_id,
                sizeof(deny.payload.access_decision.credential_id) - 1);
    }
    strncpy(deny.payload.access_decision.reason, reason,
            sizeof(deny.payload.access_decision.reason) - 1);
    deny.payload.access_decision.granted = false;
    deny.payload.access_decision.known   = false;

    event_bus_publish(&deny);
}

static void handle_heartbeat(const event_heartbeat_t *hb)
{
    /* Build protobuf request */
    portunus_v1_HeartbeatRequest req = portunus_v1_HeartbeatRequest_init_zero;

    strncpy(req.module_id, PORTUNUS_MODULE_ID, sizeof(req.module_id) - 1);
    strncpy(req.firmware_version, PORTUNUS_FW_VERSION, sizeof(req.firmware_version) - 1);
    req.uptime_s        = hb->uptime_sec;
    req.free_heap_bytes = hb->free_heap_bytes;
    req.sequence        = hb->sequence;

    if (get_sta_ip_str(req.ip, sizeof(req.ip))) {
        /* ip populated */
    }

    int32_t rssi;
    if (get_rssi(&rssi)) {
        req.has_rssi_dbm = true;
        req.rssi_dbm     = rssi;
    }

    /* Encode */
    uint8_t req_buf[portunus_v1_HeartbeatRequest_size];
    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));
    if (!pb_encode(&ostream, portunus_v1_HeartbeatRequest_fields, &req)) {
        ESP_LOGE(TAG, "Heartbeat encode failed: %s", PB_GET_ERROR(&ostream));
        return;
    }

    /* POST */
    uint8_t resp_buf[portunus_v1_HeartbeatResponse_size + 16];  /* small margin */
    int resp_len = 0;

#if PORTUNUS_USE_GRPC
    int grpc_status = 0;
    portunus_err_t err = grpc_post_proto(
        "/portunus.v1.PortunusService/SendHeartbeat",
        req_buf, ostream.bytes_written,
        resp_buf, sizeof(resp_buf),
        &resp_len, &grpc_status);
    if (err != PORTUNUS_OK) {
        ESP_LOGW(TAG, "Heartbeat gRPC failed: err=0x%04x", (unsigned)err);
        return;
    }
    if (grpc_status != GRPC_STATUS_OK) {
        ESP_LOGW(TAG, "Heartbeat gRPC status: %d", grpc_status);
        return;
    }
#else
    int status = 0;
    portunus_err_t err = http_post_proto(s_heartbeat_url,
                                         req_buf, ostream.bytes_written,
                                         resp_buf, sizeof(resp_buf),
                                         &resp_len, &status);
    if (err != PORTUNUS_OK) {
        ESP_LOGW(TAG, "Heartbeat HTTP failed: err=0x%04x", (unsigned)err);
        return;
    }

    if (status != 200) {
        ESP_LOGW(TAG, "Heartbeat server returned HTTP %d", status);
        return;
    }
#endif /* PORTUNUS_USE_GRPC */

    /* Decode response */
    portunus_v1_HeartbeatResponse resp = portunus_v1_HeartbeatResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(resp_buf, (size_t)resp_len);
    if (!pb_decode(&istream, portunus_v1_HeartbeatResponse_fields, &resp)) {
        ESP_LOGW(TAG, "Heartbeat decode failed: %s", PB_GET_ERROR(&istream));
        return;
    }

    ESP_LOGI(TAG, "Heartbeat OK — known=%d server_time=%s",
             resp.known, resp.server_time);
}

static void handle_credential(const event_credential_read_t *cred)
{
    /* Build protobuf request */
    portunus_v1_AccessRequest req = portunus_v1_AccessRequest_init_zero;

    strncpy(req.module_id, PORTUNUS_MODULE_ID, sizeof(req.module_id) - 1);
    credential_uid_to_hex(&cred->credential, req.credential_id, sizeof(req.credential_id));

    /* Encode */
    uint8_t req_buf[portunus_v1_AccessRequest_size];
    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));
    if (!pb_encode(&ostream, portunus_v1_AccessRequest_fields, &req)) {
        ESP_LOGE(TAG, "Access encode failed: %s", PB_GET_ERROR(&ostream));
        publish_access_denied(req.credential_id, "encode_error");
        return;
    }

    /* POST */
    uint8_t resp_buf[portunus_v1_AccessResponse_size + 16];
    int resp_len = 0;

#if PORTUNUS_USE_GRPC
    int grpc_status = 0;
    portunus_err_t err = grpc_post_proto(
        "/portunus.v1.PortunusService/RequestAccess",
        req_buf, ostream.bytes_written,
        resp_buf, sizeof(resp_buf),
        &resp_len, &grpc_status);
    if (err != PORTUNUS_OK) {
        ESP_LOGW(TAG, "Access gRPC failed: err=0x%04x", (unsigned)err);
        publish_access_denied(req.credential_id, "grpc_error");
        return;
    }
    if (grpc_status != GRPC_STATUS_OK) {
        ESP_LOGW(TAG, "Access gRPC status: %d", grpc_status);
        publish_access_denied(req.credential_id, "grpc_status_error");
        return;
    }
#else
    int status = 0;
    portunus_err_t err = http_post_proto(s_access_url,
                                         req_buf, ostream.bytes_written,
                                         resp_buf, sizeof(resp_buf),
                                         &resp_len, &status);
    if (err != PORTUNUS_OK) {
        ESP_LOGW(TAG, "Access HTTP failed: err=0x%04x", (unsigned)err);
        publish_access_denied(req.credential_id, "http_error");
        return;
    }

    if (status != 200) {
        ESP_LOGW(TAG, "Access server returned HTTP %d", status);
        publish_access_denied(req.credential_id, "http_status_error");
        return;
    }
#endif /* PORTUNUS_USE_GRPC */

    /* Decode response */
    portunus_v1_AccessResponse resp = portunus_v1_AccessResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(resp_buf, (size_t)resp_len);
    if (!pb_decode(&istream, portunus_v1_AccessResponse_fields, &resp)) {
        ESP_LOGW(TAG, "Access decode failed: %s", PB_GET_ERROR(&istream));
        publish_access_denied(req.credential_id, "decode_error");
        return;
    }

    ESP_LOGI(TAG, "Access decision — credential=%s granted=%d reason=%s known=%d",
             req.credential_id, resp.granted, resp.reason, resp.known);

    /* Publish decision event back to the bus */
    portunus_event_t decision;
    memset(&decision, 0, sizeof(decision));
    decision.id = resp.granted ? EVENT_ACCESS_GRANTED : EVENT_ACCESS_DENIED;

    strncpy(decision.payload.access_decision.credential_id, req.credential_id,
            sizeof(decision.payload.access_decision.credential_id) - 1);
    strncpy(decision.payload.access_decision.reason, resp.reason,
            sizeof(decision.payload.access_decision.reason) - 1);
    decision.payload.access_decision.granted = resp.granted;
    decision.payload.access_decision.known   = resp.known;

    event_bus_publish(&decision);
}

/* ── Provisioning handler (PROVISIONING_CONSOLE only) ──────────────────────── */

#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE

static void publish_provision_result(provision_result_reason_t reason,
                                     const char *member_uuid,
                                     const char *detail)
{
    portunus_event_t evt;
    memset(&evt, 0, sizeof(evt));
    evt.id = (reason == PROVISION_RESULT_SUCCESS)
             ? EVENT_PROVISION_SUCCESS
             : EVENT_PROVISION_FAILED;

    if (member_uuid) {
        strncpy(evt.payload.provision_result.member_uuid, member_uuid,
                sizeof(evt.payload.provision_result.member_uuid) - 1);
    }
    evt.payload.provision_result.reason = reason;
    if (detail) {
        strncpy(evt.payload.provision_result.detail, detail,
                sizeof(evt.payload.provision_result.detail) - 1);
    }
    event_bus_publish(&evt);
}

static void handle_provision(const event_provision_request_t *req)
{
    /* Build ProvisionCredentialRequest */
    portunus_v1_ProvisionCredentialRequest pb_req =
        portunus_v1_ProvisionCredentialRequest_init_zero;

    strncpy(pb_req.operator_uuid, req->operator_uuid,
            sizeof(pb_req.operator_uuid) - 1);
    strncpy(pb_req.module_id, PORTUNUS_MODULE_ID,
            sizeof(pb_req.module_id) - 1);
    strncpy(pb_req.role_id, req->role_id,
            sizeof(pb_req.role_id) - 1);

    pb_req.credential_hash.size = 32;
    memcpy(pb_req.credential_hash.bytes, req->credential_hash, 32);

    /* Encode */
    uint8_t req_buf[portunus_v1_ProvisionCredentialRequest_size];
    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));
    if (!pb_encode(&ostream, portunus_v1_ProvisionCredentialRequest_fields, &pb_req)) {
        ESP_LOGE(TAG, "Provision encode failed: %s", PB_GET_ERROR(&ostream));
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "encode_error");
        return;
    }

    /* Send */
    uint8_t resp_buf[portunus_v1_ProvisionCredentialResponse_size + 16];
    int resp_len = 0;

#if PORTUNUS_USE_GRPC
    int grpc_status = 0;
    portunus_err_t err = grpc_post_proto(
        "/portunus.v1.PortunusService/ProvisionCredential",
        req_buf, ostream.bytes_written,
        resp_buf, sizeof(resp_buf),
        &resp_len, &grpc_status);
    if (err != PORTUNUS_OK) {
        ESP_LOGW(TAG, "Provision gRPC failed: 0x%04x", (unsigned)err);
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "grpc_error");
        return;
    }
    if (grpc_status != GRPC_STATUS_OK) {
        ESP_LOGW(TAG, "Provision gRPC status: %d", grpc_status);
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "grpc_status_error");
        return;
    }
#else
    int http_status = 0;
    portunus_err_t err = http_post_proto(s_provision_url,
                                         req_buf, ostream.bytes_written,
                                         resp_buf, sizeof(resp_buf),
                                         &resp_len, &http_status);
    if (err != PORTUNUS_OK) {
        ESP_LOGW(TAG, "Provision HTTP failed: 0x%04x", (unsigned)err);
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "http_error");
        return;
    }
    if (http_status != 200) {
        ESP_LOGW(TAG, "Provision server returned HTTP %d", http_status);
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "http_status_error");
        return;
    }
#endif

    /* Decode response */
    portunus_v1_ProvisionCredentialResponse pb_resp =
        portunus_v1_ProvisionCredentialResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(resp_buf, (size_t)resp_len);
    if (!pb_decode(&istream, portunus_v1_ProvisionCredentialResponse_fields, &pb_resp)) {
        ESP_LOGW(TAG, "Provision decode failed: %s", PB_GET_ERROR(&istream));
        publish_provision_result(PROVISION_RESULT_COMM_ERROR, NULL, "decode_error");
        return;
    }

    ESP_LOGI(TAG, "Provision response — status=%d member_uuid=%s detail=%s",
             pb_resp.status, pb_resp.member_uuid, pb_resp.detail);

    /* Map proto status → internal reason code */
    provision_result_reason_t reason;
    switch (pb_resp.status) {
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_SUCCESS:
        reason = PROVISION_RESULT_SUCCESS;           break;
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_DUPLICATE_ACTIVE:
        reason = PROVISION_RESULT_DUPLICATE_ACTIVE;  break;
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_DUPLICATE_INACTIVE:
        reason = PROVISION_RESULT_DUPLICATE_INACTIVE; break;
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_DUPLICATE_PENDING:
        reason = PROVISION_RESULT_DUPLICATE_PENDING; break;
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_UNAUTHORIZED:
        reason = PROVISION_RESULT_UNAUTHORIZED;      break;
    case portunus_v1_ProvisionStatus_PROVISION_STATUS_INVALID_ROLE:
        reason = PROVISION_RESULT_INVALID_ROLE;      break;
    default:
        reason = PROVISION_RESULT_COMM_ERROR;        break;
    }

    publish_provision_result(reason, pb_resp.member_uuid, pb_resp.detail);
}

#endif /* CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE */

/* ── Task ──────────────────────────────────────────────────────────────────── */

static void comm_task(void *arg)
{
    (void)arg;
    portunus_event_t event;

    ESP_LOGI(TAG, "Server comm task started");

    for (;;) {
        if (xQueueReceive(s_comm_queue, &event, pdMS_TO_TICKS(1000)) != pdTRUE) {
#if PORTUNUS_USE_GRPC
            if (++s_idle_ticks >= GRPC_PING_INTERVAL_TICKS) {
                s_idle_ticks = 0;
                if (s_grpc_handle != NULL && grpc_client_is_connected(s_grpc_handle)) {
                    portunus_err_t perr = grpc_client_send_ping(s_grpc_handle);
                    if (perr != PORTUNUS_OK) {
                        ESP_LOGW(TAG, "keepalive PING failed: 0x%04x", (unsigned)perr);
                    }
                }
            }
#endif
            continue;   /* Idle tick — nothing queued */
        }

#if PORTUNUS_USE_GRPC
        s_idle_ticks = 0;  /* Reset on any RPC activity */
#endif

        if (!wifi_mgr_is_connected()) {
            ESP_LOGD(TAG, "WiFi not connected — dropping event 0x%04x",
                     (unsigned)event.id);

            /* Credential events need a deny so the FSM clears CARD_READ
               feedback.  Heartbeats can be silently dropped. */
            if (event.id == EVENT_CREDENTIAL_READ) {
                char credential_id[CREDENTIAL_UID_HEX_STR_LEN];
                credential_uid_to_hex(&event.payload.credential_read.credential,
                                      credential_id, sizeof(credential_id));
                publish_access_denied(credential_id, "no_network");
            }
            continue;
        }

        switch (event.id) {
        case EVENT_HEARTBEAT:
            handle_heartbeat(&event.payload.heartbeat);
            break;
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
        case EVENT_CREDENTIAL_READ:
            handle_credential(&event.payload.credential_read);
            break;
#endif
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
        case EVENT_PROVISION_REQUEST:
            handle_provision(&event.payload.provision_request);
            break;
#endif
        default:
            ESP_LOGW(TAG, "Unexpected event 0x%04x in comm queue",
                     (unsigned)event.id);
            break;
        }
    }
}

/* ── Public API ────────────────────────────────────────────────────────────── */

portunus_err_t server_comm_init(void)
{
    if (s_initialized) {
        ESP_LOGW(TAG, "server_comm already initialised");
        return PORTUNUS_ERR_ALREADY_INIT;
    }

    /* Configure transport — gRPC (HTTP/2) or HTTP/1.1 depending on Kconfig. */
#if PORTUNUS_USE_GRPC
    {
        grpc_client_config_t grpc_cfg = {};
        grpc_cfg.host               = PORTUNUS_SERVER_HOST;
        grpc_cfg.port               = PORTUNUS_GRPC_SERVER_PORT;
        grpc_cfg.connect_timeout_ms = PORTUNUS_SERVER_REQUEST_TIMEOUT_MS;
        grpc_cfg.rpc_timeout_ms     = PORTUNUS_SERVER_REQUEST_TIMEOUT_MS;
        grpc_cfg.skip_cert_verify   = PORTUNUS_TLS_SKIP_VERIFY;

      #if PORTUNUS_TLS_USE_CUSTOM_CA
        grpc_cfg.ca_cert_pem = ca_cert_pem_start;
      #else
        grpc_cfg.ca_cert_pem = NULL; /* Use ESP-IDF cert bundle */
      #endif

        portunus_err_t grpc_err = grpc_client_init(&grpc_cfg, &s_grpc_handle);
        if (grpc_err != PORTUNUS_OK) {
            ESP_LOGE(TAG, "gRPC client init failed: 0x%04x", (unsigned)grpc_err);
            return grpc_err;
        }
        ESP_LOGI(TAG, "Transport: gRPC (HTTP/2+TLS) → %s:%d",
                 PORTUNUS_SERVER_HOST, PORTUNUS_GRPC_SERVER_PORT);
    }
#else
    /* Build URLs once — scheme and port are driven by TLS Kconfig. */
  #if PORTUNUS_USE_TLS
    snprintf(s_heartbeat_url, sizeof(s_heartbeat_url),
             "https://%s:%d/v1/heartbeat",
             PORTUNUS_SERVER_HOST, PORTUNUS_TLS_SERVER_PORT);
    snprintf(s_access_url, sizeof(s_access_url),
             "https://%s:%d/v1/access_request",
             PORTUNUS_SERVER_HOST, PORTUNUS_TLS_SERVER_PORT);
    #ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
    snprintf(s_provision_url, sizeof(s_provision_url),
             "https://%s:%d/v1/provision_credential",
             PORTUNUS_SERVER_HOST, PORTUNUS_TLS_SERVER_PORT);
    #endif
  #else
    snprintf(s_heartbeat_url, sizeof(s_heartbeat_url),
             "http://%s:%d/v1/heartbeat",
             PORTUNUS_SERVER_HOST, PORTUNUS_SERVER_PORT);
    snprintf(s_access_url, sizeof(s_access_url),
             "http://%s:%d/v1/access_request",
             PORTUNUS_SERVER_HOST, PORTUNUS_SERVER_PORT);
    #ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
    snprintf(s_provision_url, sizeof(s_provision_url),
             "http://%s:%d/v1/provision_credential",
             PORTUNUS_SERVER_HOST, PORTUNUS_SERVER_PORT);
    #endif
  #endif

    ESP_LOGI(TAG, "Transport: HTTP/1.1");
    ESP_LOGI(TAG, "Heartbeat URL: %s", s_heartbeat_url);
    #ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
    ESP_LOGI(TAG, "Access URL:    %s", s_access_url);
    #else
    ESP_LOGI(TAG, "Provision URL: %s", s_provision_url);
    #endif
#endif /* PORTUNUS_USE_GRPC */

    /* Create internal queue */
    s_comm_queue = xQueueCreate(COMM_QUEUE_LENGTH, sizeof(portunus_event_t));
    if (s_comm_queue == NULL) {
        ESP_LOGE(TAG, "Failed to create comm queue");
        return PORTUNUS_ERR_QUEUE_CREATE;
    }

    /* Subscribe to events */
    portunus_err_t sub_err;

    sub_err = event_bus_subscribe(EVENT_HEARTBEAT, on_heartbeat_event, NULL);
    if (sub_err != PORTUNUS_OK) {
        ESP_LOGE(TAG, "Failed to subscribe to heartbeat events: 0x%04x", (unsigned)sub_err);
    }

#ifdef CONFIG_PORTUNUS_MODULE_TYPE_ACCESS_POINT
    sub_err = event_bus_subscribe(EVENT_CREDENTIAL_READ, on_credential_event, NULL);
    if (sub_err != PORTUNUS_OK) {
        ESP_LOGE(TAG, "Failed to subscribe to credential events: 0x%04x", (unsigned)sub_err);
    }
#endif
#ifdef CONFIG_PORTUNUS_MODULE_TYPE_PROVISIONING_CONSOLE
    sub_err = event_bus_subscribe(EVENT_PROVISION_REQUEST, on_provision_event, NULL);
    if (sub_err != PORTUNUS_OK) {
        ESP_LOGE(TAG, "Failed to subscribe to provision events: 0x%04x", (unsigned)sub_err);
    }
#endif

    /* Start task */
    BaseType_t ret = xTaskCreate(
        comm_task,
        "server_comm",
        COMM_TASK_STACK_SIZE,
        NULL,
        COMM_TASK_PRIORITY,
        &s_comm_task
    );
    if (ret != pdPASS) {
        ESP_LOGE(TAG, "Failed to create comm task");
        return PORTUNUS_ERR_TASK_CREATE;
    }

    s_initialized = true;
    ESP_LOGI(TAG, "Server comm initialised");
    return PORTUNUS_OK;
}

void server_comm_deinit(void)
{
    if (!s_initialized) {
        return;
    }

    /* Delete the network task first so it stops pulling from the queue. */
    if (s_comm_task != NULL) {
        vTaskDelete(s_comm_task);
        s_comm_task = NULL;
    }

    /* Drain and delete the internal queue. */
    if (s_comm_queue != NULL) {
        portunus_event_t discarded;
        while (xQueueReceive(s_comm_queue, &discarded, 0) == pdTRUE) {
            /* discard */
        }
        vQueueDelete(s_comm_queue);
        s_comm_queue = NULL;
    }

#if PORTUNUS_USE_GRPC
    /* Destroy the gRPC client (closes TLS + HTTP/2 session). */
    if (s_grpc_handle != NULL) {
        grpc_client_destroy(s_grpc_handle);
        s_grpc_handle = NULL;
    }
#endif

    s_initialized = false;
    ESP_LOGI(TAG, "Server comm deinitialised");
}